//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tam.Maestro.Data.EntityFrameworkMapping.BroadcastForecast
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BroadcastForecastContext : DbContext
    {
        public BroadcastForecastContext()
            : base("name=BroadcastForecastContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<universe> universes { get; set; }
        public virtual DbSet<usage> usages { get; set; }
        public virtual DbSet<viewer_details> viewer_details { get; set; }
        public virtual DbSet<code> codes { get; set; }
        public virtual DbSet<post_months> post_months { get; set; }
        public virtual DbSet<viewers> viewers { get; set; }
        public virtual DbSet<market_headers> market_headers { get; set; }
        public virtual DbSet<usages_arc> usages_arc { get; set; }
        public virtual DbSet<usages_trunc> usages_trunc { get; set; }
        public virtual DbSet<viewer_details_arc> viewer_details_arc { get; set; }
        public virtual DbSet<viewer_details_trunc> viewer_details_trunc { get; set; }
        public virtual DbSet<viewers_arc> viewers_arc { get; set; }
        public virtual DbSet<viewers_trunc> viewers_trunc { get; set; }
        public virtual DbSet<stations> stations { get; set; }
        public virtual DbSet<vpvh_quarters> vpvh_quarters { get; set; }
    
        public virtual int usp_ForecastNsiRatingsMonth(Nullable<short> media_month_id)
        {
            var media_month_idParameter = media_month_id.HasValue ?
                new ObjectParameter("media_month_id", media_month_id) :
                new ObjectParameter("media_month_id", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ForecastNsiRatingsMonth", media_month_idParameter);
        }
    }
}
