//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tam.Maestro.Data.EntityFrameworkMapping.BroadcastForecast
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BroadcastForecastContext : DbContext
    {
        public BroadcastForecastContext()
            : base("name=BroadcastForecastContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<universe> universes { get; set; }
        public virtual DbSet<usage> usages { get; set; }
        public virtual DbSet<viewer_details> viewer_details { get; set; }
        public virtual DbSet<viewer> viewers { get; set; }
    
        public virtual int usp_ForecastNsiRatingsMonth(Nullable<short> media_month_id, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date)
        {
            var media_month_idParameter = media_month_id.HasValue ?
                new ObjectParameter("media_month_id", media_month_id) :
                new ObjectParameter("media_month_id", typeof(short));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ForecastNsiRatingsMonth", media_month_idParameter, start_dateParameter, end_dateParameter);
        }
    }
}
