//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tam.Maestro.Data.EntityFrameworkMapping.BroadcastForecast
{
    using System;
    using System.Collections.Generic;
    
    public partial class market_headers
    {
        public int media_month_id { get; set; }
        public string file_name { get; set; }
        public Nullable<int> dma_id { get; set; }
        public string format_version { get; set; }
        public short market_code { get; set; }
        public short dma_code { get; set; }
        public Nullable<short> market_rank { get; set; }
        public string geography_indicator { get; set; }
        public string geography_name { get; set; }
        public System.DateTime start_datetime_of_survey { get; set; }
        public System.DateTime end_datetime_of_survey { get; set; }
        public short number_of_days_in_survey { get; set; }
        public short number_of_weeks_in_survey { get; set; }
        public System.TimeSpan reporting_day_start_time { get; set; }
        public string reporting_service { get; set; }
        public string special_report_exclusion_indicator { get; set; }
        public string subsample_indicator { get; set; }
        public string header_sample_type { get; set; }
        public bool reissued { get; set; }
        public bool data_accredited { get; set; }
        public string playback_type { get; set; }
        public int time_interval { get; set; }
        public string collection_method { get; set; }
        public bool contest_indicator { get; set; }
        public string report_period { get; set; }
        public short report_year { get; set; }
        public short market_time_zone { get; set; }
        public string market_class_code { get; set; }
        public bool distributor_or_market_exclusion_indicator { get; set; }
        public bool daylight_savings_time_indicator { get; set; }
    }
}
