//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tam.Maestro.Data.EntityFrameworkMapping.BroadcastForecast
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewer
    {
        public short media_month_id { get; set; }
        public short station_code { get; set; }
        public int start_time { get; set; }
        public int end_time { get; set; }
        public short market_code { get; set; }
        public long id { get; set; }
    }
}
