import { createAction } from "../actionCreator";

export const POST_PRE_POSTING_INITIALDATA = createAction(
  "POST_PRE_POSTING_INITIALDATA"
);
export const POST_PRE_POSTING = createAction("POST_PRE_POSTING");
export const FILTERED_POST_PRE_POSTING = createAction(
  "FILTERED_POST_PRE_POSTING"
);
export const DELETE_POST_PRE_POSTING = createAction("DELETE_POST_PRE_POSTING");
export const POST_PRE_POSTING_FILE_EDIT = createAction(
  "POST_PRE_POSTING_FILE_EDIT"
);
export const POST_PRE_POSTING_FILE_SAVE = createAction(
  "POST_PRE_POSTING_FILE_SAVE"
);
export const POST_PRE_POSTING_FILE_UPLOAD = createAction(
  "POST_PRE_POSTING_FILE_UPLOAD"
);

export const TOGGLE_MODAL = "TOGGLE_MODAL";

export const FILE_EDIT_FORM_UPDATE_EQUIVALIZED =
  "FILE_EDIT_FORM_UPDATE_EQUIVALIZED";
export const FILE_EDIT_FORM_UPDATE_POSTING_BOOK =
  "FILE_EDIT_FORM_UPDATE_POSTING_BOOK";
export const FILE_EDIT_FORM_UPDATE_PLAYBACK_TYPE =
  "FILE_EDIT_FORM_UPDATE_PLAYBACK_TYPE";
export const FILE_EDIT_FORM_UPDATE_DEMOS = "FILE_EDIT_FORM_UPDATE_DEMOS";

export const FILE_UPLOAD_FORM_UPDATE_EQUIVALIZED =
  "FILE_UPLOAD_FORM_UPDATE_EQUIVALIZED";
export const FILE_UPLOAD_FORM_UPDATE_POSTING_BOOK =
  "FILE_UPLOAD_FORM_UPDATE_POSTING_BOOK";
export const FILE_UPLOAD_FORM_UPDATE_PLAYBACK_TYPE =
  "FILE_UPLOAD_FORM_UPDATE_PLAYBACK_TYPE";
export const FILE_UPLOAD_FORM_UPDATE_DEMOS = "FILE_UPLOAD_FORM_UPDATE_DEMOS";
export const CLEAR_FILE_UPLOAD_FORM = "CLEAR_FILE_UPLOAD_FORM";
