CREATE PARTITION SCHEME [MediaMonthIDPScheme]
    AS PARTITION [MediaMonthIDRangePFN]
    TO ([PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PRIMARY], [PARTITION_FILES]);



