CREATE PARTITION SCHEME [MediaMonthSmallintScheme]
    AS PARTITION [MediaMonthSmallintPFN]
    TO ([PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES]);



