CREATE PARTITION SCHEME [MediaMonthIDRatingScheme]
    AS PARTITION [MediaMonthIDRatingFN]
    TO ([PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES]);



