CREATE PARTITION SCHEME [MediaMonthScheme]
    AS PARTITION [MediaMonthPFN]
    TO ([PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES], [PARTITION_FILES]);



