//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class affidavit_outbound_files
    {
        public affidavit_outbound_files()
        {
            this.affidavit_outbound_file_problems = new HashSet<affidavit_outbound_file_problems>();
        }
    
        public int id { get; set; }
        public string file_name { get; set; }
        public string file_hash { get; set; }
        public int source_id { get; set; }
        public int status { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
    
        public virtual ICollection<affidavit_outbound_file_problems> affidavit_outbound_file_problems { get; set; }
    }
}
