//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class affidavit_file_detail_audiences
    {
        public long affidavit_file_detail_id { get; set; }
        public int audience_id { get; set; }
        public double impressions { get; set; }
    
        public virtual affidavit_file_details affidavit_file_details { get; set; }
        public virtual audience audience { get; set; }
    }
}
