//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class affidavit_files
    {
        public affidavit_files()
        {
            this.affidavit_file_details = new HashSet<affidavit_file_details>();
        }
    
        public int id { get; set; }
        public string file_name { get; set; }
        public string file_hash { get; set; }
        public int source_id { get; set; }
        public System.DateTime created_date { get; set; }
        public int media_month_id { get; set; }
    
        public virtual ICollection<affidavit_file_details> affidavit_file_details { get; set; }
    }
}
