//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class affidavit_outbound_file_problems
    {
        public int id { get; set; }
        public Nullable<int> affidavit_outbound_file_id { get; set; }
        public string problem_description { get; set; }
    
        public virtual affidavit_outbound_files affidavit_outbound_files { get; set; }
    }
}
