//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BroadcastContext : DbContext
    {
        public BroadcastContext()
            : base("name=BroadcastContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<audience_audiences> audience_audiences { get; set; }
        public virtual DbSet<audience> audiences { get; set; }
        public virtual DbSet<bvs_file_details> bvs_file_details { get; set; }
        public virtual DbSet<bvs_files> bvs_files { get; set; }
        public virtual DbSet<bvs_maps> bvs_maps { get; set; }
        public virtual DbSet<bvs_post_details> bvs_post_details { get; set; }
        public virtual DbSet<daypart> dayparts { get; set; }
        public virtual DbSet<day> days { get; set; }
        public virtual DbSet<market_dma_map> market_dma_map { get; set; }
        public virtual DbSet<media_months> media_months { get; set; }
        public virtual DbSet<media_weeks> media_weeks { get; set; }
        public virtual DbSet<post_file_demos> post_file_demos { get; set; }
        public virtual DbSet<post_file_detail_impressions> post_file_detail_impressions { get; set; }
        public virtual DbSet<post_file_details> post_file_details { get; set; }
        public virtual DbSet<post_files> post_files { get; set; }
        public virtual DbSet<proposal_version_flight_weeks> proposal_version_flight_weeks { get; set; }
        public virtual DbSet<proposal_version_markets> proposal_version_markets { get; set; }
        public virtual DbSet<proposal_version_spot_length> proposal_version_spot_length { get; set; }
        public virtual DbSet<proposal> proposals { get; set; }
        public virtual DbSet<rating_adjustments> rating_adjustments { get; set; }
        public virtual DbSet<schedule_detail_audiences> schedule_detail_audiences { get; set; }
        public virtual DbSet<schedule_detail_weeks> schedule_detail_weeks { get; set; }
        public virtual DbSet<schedule_details> schedule_details { get; set; }
        public virtual DbSet<schedule_iscis> schedule_iscis { get; set; }
        public virtual DbSet<schedule_restriction_dayparts> schedule_restriction_dayparts { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<spot_length_cost_multipliers> spot_length_cost_multipliers { get; set; }
        public virtual DbSet<station_contacts> station_contacts { get; set; }
        public virtual DbSet<system_component_parameters> system_component_parameters { get; set; }
        public virtual DbSet<timespan> timespans { get; set; }
        public virtual DbSet<vw_ccc_daypart> vw_ccc_daypart { get; set; }
        public virtual DbSet<proposal_version_audiences> proposal_version_audiences { get; set; }
        public virtual DbSet<proposal_version_detail_quarters> proposal_version_detail_quarters { get; set; }
        public virtual DbSet<proposal_version_detail_quarter_weeks> proposal_version_detail_quarter_weeks { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<proposal_version_detail_criteria_cpm> proposal_version_detail_criteria_cpm { get; set; }
        public virtual DbSet<proposal_version_detail_criteria_genres> proposal_version_detail_criteria_genres { get; set; }
        public virtual DbSet<rep_firms> rep_firms { get; set; }
        public virtual DbSet<bvs_map_types> bvs_map_types { get; set; }
        public virtual DbSet<schedule_audiences> schedule_audiences { get; set; }
        public virtual DbSet<inventory_sources> inventory_sources { get; set; }
        public virtual DbSet<station_inventory_group> station_inventory_group { get; set; }
        public virtual DbSet<station_inventory_manifest_generation> station_inventory_manifest_generation { get; set; }
        public virtual DbSet<spot_lengths> spot_lengths { get; set; }
        public virtual DbSet<station_inventory_manifest_dayparts> station_inventory_manifest_dayparts { get; set; }
        public virtual DbSet<station_inventory_manifest> station_inventory_manifest { get; set; }
        public virtual DbSet<station_inventory_spot_audiences> station_inventory_spot_audiences { get; set; }
        public virtual DbSet<station_inventory_spots> station_inventory_spots { get; set; }
        public virtual DbSet<proposal_version_detail_quarter_week_iscis> proposal_version_detail_quarter_week_iscis { get; set; }
        public virtual DbSet<affidavit_files> affidavit_files { get; set; }
        public virtual DbSet<nsi_component_audiences> nsi_component_audiences { get; set; }
        public virtual DbSet<affidavit_file_detail_problems> affidavit_file_detail_problems { get; set; }
        public virtual DbSet<proposal_version_detail_criteria_programs> proposal_version_detail_criteria_programs { get; set; }
        public virtual DbSet<program_names> program_names { get; set; }
        public virtual DbSet<affidavit_outbound_file_problems> affidavit_outbound_file_problems { get; set; }
        public virtual DbSet<affidavit_outbound_files> affidavit_outbound_files { get; set; }
        public virtual DbSet<proposal_version_detail_criteria_show_types> proposal_version_detail_criteria_show_types { get; set; }
        public virtual DbSet<show_types> show_types { get; set; }
        public virtual DbSet<affidavit_file_problems> affidavit_file_problems { get; set; }
        public virtual DbSet<affidavit_file_detail_demographics> affidavit_file_detail_demographics { get; set; }
        public virtual DbSet<isci_mapping> isci_mapping { get; set; }
        public virtual DbSet<postlog_outbound_file_problems> postlog_outbound_file_problems { get; set; }
        public virtual DbSet<postlog_outbound_files> postlog_outbound_files { get; set; }
        public virtual DbSet<proposal_versions> proposal_versions { get; set; }
        public virtual DbSet<spot_tracker_file_details> spot_tracker_file_details { get; set; }
        public virtual DbSet<spot_tracker_files> spot_tracker_files { get; set; }
        public virtual DbSet<proposal_buy_file_detail_audiences> proposal_buy_file_detail_audiences { get; set; }
        public virtual DbSet<proposal_buy_file_detail_weeks> proposal_buy_file_detail_weeks { get; set; }
        public virtual DbSet<proposal_buy_file_details> proposal_buy_file_details { get; set; }
        public virtual DbSet<proposal_buy_files> proposal_buy_files { get; set; }
        public virtual DbSet<market_coverages> market_coverages { get; set; }
        public virtual DbSet<postlog_file_detail_demographics> postlog_file_detail_demographics { get; set; }
        public virtual DbSet<postlog_file_detail_problems> postlog_file_detail_problems { get; set; }
        public virtual DbSet<postlog_file_problems> postlog_file_problems { get; set; }
        public virtual DbSet<postlog_files> postlog_files { get; set; }
        public virtual DbSet<isci_blacklist> isci_blacklist { get; set; }
        public virtual DbSet<postlog_client_scrub_audiences> postlog_client_scrub_audiences { get; set; }
        public virtual DbSet<station_inventory_manifest_genres> station_inventory_manifest_genres { get; set; }
        public virtual DbSet<station_inventory_manifest_daypart_genres> station_inventory_manifest_daypart_genres { get; set; }
        public virtual DbSet<affidavit_client_scrubs> affidavit_client_scrubs { get; set; }
        public virtual DbSet<affidavit_client_scrub_audiences> affidavit_client_scrub_audiences { get; set; }
        public virtual DbSet<postlog_client_scrubs> postlog_client_scrubs { get; set; }
        public virtual DbSet<postlog_file_details> postlog_file_details { get; set; }
        public virtual DbSet<affidavit_file_details> affidavit_file_details { get; set; }
        public virtual DbSet<station_inventory_manifest_staging> station_inventory_manifest_staging { get; set; }
        public virtual DbSet<pricing_guide_distribution_proprietary_inventory> pricing_guide_distribution_proprietary_inventory { get; set; }
        public virtual DbSet<proposal_version_details> proposal_version_details { get; set; }
        public virtual DbSet<nti_transmittals_file_problems> nti_transmittals_file_problems { get; set; }
        public virtual DbSet<nti_transmittals_file_report_ratings> nti_transmittals_file_report_ratings { get; set; }
        public virtual DbSet<nti_transmittals_file_reports> nti_transmittals_file_reports { get; set; }
        public virtual DbSet<nti_transmittals_files> nti_transmittals_files { get; set; }
        public virtual DbSet<pricing_guide_distribution_open_market_inventory> pricing_guide_distribution_open_market_inventory { get; set; }
        public virtual DbSet<pricing_guide_distributions> pricing_guide_distributions { get; set; }
        public virtual DbSet<station_inventory_spot_snapshots> station_inventory_spot_snapshots { get; set; }
        public virtual DbSet<nti_transmittals_audiences> nti_transmittals_audiences { get; set; }
        public virtual DbSet<market_coverage_files> market_coverage_files { get; set; }
        public virtual DbSet<station_inventory_loaded> station_inventory_loaded { get; set; }
        public virtual DbSet<inventory_files> inventory_files { get; set; }
        public virtual DbSet<inventory_file_problems> inventory_file_problems { get; set; }
        public virtual DbSet<market> markets { get; set; }
        public virtual DbSet<station_inventory_manifest_audiences> station_inventory_manifest_audiences { get; set; }
        public virtual DbSet<station_inventory_manifest_rates> station_inventory_manifest_rates { get; set; }
        public virtual DbSet<station_inventory_manifest_weeks> station_inventory_manifest_weeks { get; set; }
        public virtual DbSet<station> stations { get; set; }
        public virtual DbSet<inventory_file_ratings_jobs> inventory_file_ratings_jobs { get; set; }
        public virtual DbSet<daypart_codes> daypart_codes { get; set; }
        public virtual DbSet<inventory_file_proprietary_header> inventory_file_proprietary_header { get; set; }
        public virtual DbSet<station_inventory_manifest_weeks_history> station_inventory_manifest_weeks_history { get; set; }
        public virtual DbSet<inventory_source_logos> inventory_source_logos { get; set; }
        public virtual DbSet<audience_maps> audience_maps { get; set; }
        public virtual DbSet<scx_generation_job_files> scx_generation_job_files { get; set; }
        public virtual DbSet<scx_generation_job_units> scx_generation_job_units { get; set; }
        public virtual DbSet<scx_generation_jobs> scx_generation_jobs { get; set; }
        public virtual DbSet<inventory_summary> inventory_summary { get; set; }
        public virtual DbSet<inventory_summary_gap_ranges> inventory_summary_gap_ranges { get; set; }
        public virtual DbSet<inventory_summary_gaps> inventory_summary_gaps { get; set; }
        public virtual DbSet<inventory_summary_quarters> inventory_summary_quarters { get; set; }
        public virtual DbSet<inventory_summary_quarter_details> inventory_summary_quarter_details { get; set; }
        public virtual DbSet<campaign> campaigns { get; set; }
        public virtual DbSet<campaign_summaries> campaign_summaries { get; set; }
        public virtual DbSet<inventory_file_ratings_job_notes> inventory_file_ratings_job_notes { get; set; }
        public virtual DbSet<inventory_file_program_names_jobs> inventory_file_program_names_jobs { get; set; }
        public virtual DbSet<genre_mappings> genre_mappings { get; set; }
        public virtual DbSet<genre_sources> genre_sources { get; set; }
        public virtual DbSet<plan_version_available_markets> plan_version_available_markets { get; set; }
        public virtual DbSet<plan_version_blackout_markets> plan_version_blackout_markets { get; set; }
        public virtual DbSet<plan_version_dayparts> plan_version_dayparts { get; set; }
        public virtual DbSet<plan_version_flight_hiatus_days> plan_version_flight_hiatus_days { get; set; }
        public virtual DbSet<plan_version_secondary_audiences> plan_version_secondary_audiences { get; set; }
        public virtual DbSet<plan_version_summaries> plan_version_summaries { get; set; }
        public virtual DbSet<plan_version_weeks> plan_version_weeks { get; set; }
        public virtual DbSet<plan> plans { get; set; }
        public virtual DbSet<plan_versions> plan_versions { get; set; }
        public virtual DbSet<plan_version_summary_quarters> plan_version_summary_quarters { get; set; }
    }
}
