//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class custom_daypart_organizations
    {
        public custom_daypart_organizations()
        {
            this.plan_version_daypart_customizations = new HashSet<plan_version_daypart_customizations>();
        }
    
        public int id { get; set; }
        public string organization_name { get; set; }
    
        public virtual ICollection<plan_version_daypart_customizations> plan_version_daypart_customizations { get; set; }
    }
}
