//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class day
    {
        public day()
        {
            this.dayparts = new HashSet<daypart>();
        }
    
        public int id { get; set; }
        public string code_1 { get; set; }
        public string code_2 { get; set; }
        public string code_3 { get; set; }
        public string name { get; set; }
        public int ordinal { get; set; }
    
        public virtual ICollection<daypart> dayparts { get; set; }
    }
}
