//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class daypart_codes
    {
        public daypart_codes()
        {
            this.inventory_file_proprietary_header = new HashSet<inventory_file_proprietary_header>();
            this.station_inventory_manifest_dayparts = new HashSet<station_inventory_manifest_dayparts>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public bool is_active { get; set; }
        public string full_name { get; set; }
    
        public virtual ICollection<inventory_file_proprietary_header> inventory_file_proprietary_header { get; set; }
        public virtual ICollection<station_inventory_manifest_dayparts> station_inventory_manifest_dayparts { get; set; }
    }
}
