//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class detection_post_details
    {
        public int detection_file_detail_id { get; set; }
        public int audience_id { get; set; }
        public double delivery { get; set; }
        public Nullable<int> audience_rank { get; set; }
    
        public virtual audience audience { get; set; }
        public virtual detection_file_details detection_file_details { get; set; }
    }
}
