//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class detection_files
    {
        public detection_files()
        {
            this.detection_file_details = new HashSet<detection_file_details>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string file_hash { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_date { get; set; }
    
        public virtual ICollection<detection_file_details> detection_file_details { get; set; }
    }
}
