//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class detection_map_types
    {
        public detection_map_types()
        {
            this.detection_maps = new HashSet<detection_maps>();
        }
    
        public int id { get; set; }
        public string display { get; set; }
        public int version { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_date { get; set; }
    
        public virtual ICollection<detection_maps> detection_maps { get; set; }
    }
}
