//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_proprietary_summary_audiences
    {
        public int id { get; set; }
        public int inventory_proprietary_summary_id { get; set; }
        public int audience_id { get; set; }
        public Nullable<double> impressions { get; set; }
    
        public virtual audience audience { get; set; }
        public virtual inventory_proprietary_summary inventory_proprietary_summary { get; set; }
    }
}
