//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_export_jobs
    {
        public int id { get; set; }
        public int inventory_source_id { get; set; }
        public int quarter_year { get; set; }
        public int quarter_number { get; set; }
        public int export_genre_type_id { get; set; }
        public int status { get; set; }
        public string status_message { get; set; }
        public string file_name { get; set; }
        public Nullable<System.DateTime> completed_at { get; set; }
        public System.DateTime created_at { get; set; }
        public string created_by { get; set; }
    
        public virtual inventory_sources inventory_sources { get; set; }
    }
}
