//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_summary_quarter_details
    {
        public int id { get; set; }
        public int inventory_summary_quarter_id { get; set; }
        public int total_markets { get; set; }
        public double total_coverage { get; set; }
        public Nullable<int> total_units { get; set; }
        public Nullable<int> total_programs { get; set; }
        public Nullable<double> total_projected_impressions { get; set; }
        public Nullable<decimal> cpm { get; set; }
        public Nullable<int> min_spots_per_week { get; set; }
        public Nullable<int> max_spots_per_week { get; set; }
        public int daypart_default_id { get; set; }
    
        public virtual inventory_summary_quarters inventory_summary_quarters { get; set; }
        public virtual daypart_defaults daypart_defaults { get; set; }
    }
}
