//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_source_logos
    {
        public int id { get; set; }
        public int inventory_source_id { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public string file_name { get; set; }
        public byte[] file_content { get; set; }
    
        public virtual inventory_sources inventory_sources { get; set; }
    }
}
