//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_programs_by_file_job_notes
    {
        public int id { get; set; }
        public int job_id { get; set; }
        public string text { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual inventory_programs_by_file_jobs inventory_programs_by_file_jobs { get; set; }
    }
}
