//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_detail_slot_proposal
    {
        public int inventory_detail_slot_id { get; set; }
        public int proprosal_version_detail_quarter_week_id { get; set; }
        public int order { get; set; }
        public string created_by { get; set; }
        public string isci { get; set; }
        public int rolled_up_daypart_id { get; set; }
        public decimal slot_cost { get; set; }
        public int spot_length_id { get; set; }
        public int impressions { get; set; }
    
        public virtual proposal_version_detail_quarter_weeks proposal_version_detail_quarter_weeks { get; set; }
    }
}
