//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class isci_mapping
    {
        public int id { get; set; }
        public string original_isci { get; set; }
        public string effective_isci { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
    }
}
