//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class market_time_zones
    {
        public int id { get; set; }
        public short market_code { get; set; }
        public int time_zone_id { get; set; }
    
        public virtual market market { get; set; }
        public virtual time_zones time_zones { get; set; }
    }
}
