//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class media_weeks
    {
        public media_weeks()
        {
            this.proposal_version_flight_weeks = new HashSet<proposal_version_flight_weeks>();
            this.schedule_detail_weeks = new HashSet<schedule_detail_weeks>();
            this.proposal_version_detail_quarter_weeks = new HashSet<proposal_version_detail_quarter_weeks>();
            this.station_inventory_manifest_generation = new HashSet<station_inventory_manifest_generation>();
            this.proposal_buy_file_detail_weeks = new HashSet<proposal_buy_file_detail_weeks>();
            this.station_inventory_manifest_weeks = new HashSet<station_inventory_manifest_weeks>();
            this.plan_version_pricing_api_result_spots = new HashSet<plan_version_pricing_api_result_spots>();
            this.plan_version_pricing_api_result_spots1 = new HashSet<plan_version_pricing_api_result_spots>();
            this.plan_version_buying_api_result_spots = new HashSet<plan_version_buying_api_result_spots>();
            this.plan_version_buying_api_result_spots1 = new HashSet<plan_version_buying_api_result_spots>();
            this.plan_version_daypart_weekly_breakdown = new HashSet<plan_version_daypart_weekly_breakdown>();
            this.plan_version_weekly_breakdown = new HashSet<plan_version_weekly_breakdown>();
        }
    
        public int id { get; set; }
        public int media_month_id { get; set; }
        public int week_number { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual media_months media_months { get; set; }
        public virtual ICollection<proposal_version_flight_weeks> proposal_version_flight_weeks { get; set; }
        public virtual ICollection<schedule_detail_weeks> schedule_detail_weeks { get; set; }
        public virtual ICollection<proposal_version_detail_quarter_weeks> proposal_version_detail_quarter_weeks { get; set; }
        public virtual ICollection<station_inventory_manifest_generation> station_inventory_manifest_generation { get; set; }
        public virtual ICollection<proposal_buy_file_detail_weeks> proposal_buy_file_detail_weeks { get; set; }
        public virtual ICollection<station_inventory_manifest_weeks> station_inventory_manifest_weeks { get; set; }
        public virtual ICollection<plan_version_pricing_api_result_spots> plan_version_pricing_api_result_spots { get; set; }
        public virtual ICollection<plan_version_pricing_api_result_spots> plan_version_pricing_api_result_spots1 { get; set; }
        public virtual ICollection<plan_version_buying_api_result_spots> plan_version_buying_api_result_spots { get; set; }
        public virtual ICollection<plan_version_buying_api_result_spots> plan_version_buying_api_result_spots1 { get; set; }
        public virtual ICollection<plan_version_daypart_weekly_breakdown> plan_version_daypart_weekly_breakdown { get; set; }
        public virtual ICollection<plan_version_weekly_breakdown> plan_version_weekly_breakdown { get; set; }
    }
}
