//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class media_months
    {
        public media_months()
        {
            this.media_weeks = new HashSet<media_weeks>();
            this.post_files = new HashSet<post_files>();
            this.schedules = new HashSet<schedule>();
            this.proposal_version_details = new HashSet<proposal_version_details>();
            this.proposal_version_details1 = new HashSet<proposal_version_details>();
            this.proposal_version_details2 = new HashSet<proposal_version_details>();
            this.proposal_version_details3 = new HashSet<proposal_version_details>();
            this.inventory_file_proprietary_header = new HashSet<inventory_file_proprietary_header>();
            this.inventory_file_proprietary_header1 = new HashSet<inventory_file_proprietary_header>();
            this.nti_to_nsi_conversion_rates = new HashSet<nti_to_nsi_conversion_rates>();
            this.station_month_details = new HashSet<station_month_details>();
            this.plan_versions = new HashSet<plan_versions>();
            this.plan_versions1 = new HashSet<plan_versions>();
        }
    
        public int id { get; set; }
        public int year { get; set; }
        public int month { get; set; }
        public string media_month { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual ICollection<media_weeks> media_weeks { get; set; }
        public virtual ICollection<post_files> post_files { get; set; }
        public virtual rating_adjustments rating_adjustments { get; set; }
        public virtual ICollection<schedule> schedules { get; set; }
        public virtual ICollection<proposal_version_details> proposal_version_details { get; set; }
        public virtual ICollection<proposal_version_details> proposal_version_details1 { get; set; }
        public virtual ICollection<proposal_version_details> proposal_version_details2 { get; set; }
        public virtual ICollection<proposal_version_details> proposal_version_details3 { get; set; }
        public virtual ICollection<inventory_file_proprietary_header> inventory_file_proprietary_header { get; set; }
        public virtual ICollection<inventory_file_proprietary_header> inventory_file_proprietary_header1 { get; set; }
        public virtual ICollection<nti_to_nsi_conversion_rates> nti_to_nsi_conversion_rates { get; set; }
        public virtual ICollection<station_month_details> station_month_details { get; set; }
        public virtual ICollection<plan_versions> plan_versions { get; set; }
        public virtual ICollection<plan_versions> plan_versions1 { get; set; }
    }
}
