//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class media_weeks
    {
        public media_weeks()
        {
            this.proposal_version_flight_weeks = new HashSet<proposal_version_flight_weeks>();
            this.schedule_detail_weeks = new HashSet<schedule_detail_weeks>();
            this.proposal_version_detail_quarter_weeks = new HashSet<proposal_version_detail_quarter_weeks>();
        }
    
        public int id { get; set; }
        public int media_month_id { get; set; }
        public int week_number { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual media_months media_months { get; set; }
        public virtual ICollection<proposal_version_flight_weeks> proposal_version_flight_weeks { get; set; }
        public virtual ICollection<schedule_detail_weeks> schedule_detail_weeks { get; set; }
        public virtual ICollection<proposal_version_detail_quarter_weeks> proposal_version_detail_quarter_weeks { get; set; }
    }
}
