//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class nsi_component_audiences
    {
        public int audience_id { get; set; }
        public byte category_code { get; set; }
        public string sub_category_code { get; set; }
        public Nullable<int> range_start { get; set; }
        public Nullable<int> range_end { get; set; }
        public bool custom { get; set; }
        public string code { get; set; }
        public string name { get; set; }
    
        public virtual audience audience { get; set; }
    }
}
