//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class nti_transmittals_audiences
    {
        public int id { get; set; }
        public int nti_transmittals_file_report_id { get; set; }
        public int proposal_version_detail_quarter_week_id { get; set; }
        public int audience_id { get; set; }
        public double impressions { get; set; }
    
        public virtual audience audience { get; set; }
        public virtual nti_transmittals_file_reports nti_transmittals_file_reports { get; set; }
        public virtual proposal_version_detail_quarter_weeks proposal_version_detail_quarter_weeks { get; set; }
    }
}
