//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class nti_transmittals_files
    {
        public nti_transmittals_files()
        {
            this.nti_transmittals_file_problems = new HashSet<nti_transmittals_file_problems>();
            this.nti_transmittals_file_reports = new HashSet<nti_transmittals_file_reports>();
        }
    
        public int id { get; set; }
        public string file_name { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<nti_transmittals_file_problems> nti_transmittals_file_problems { get; set; }
        public virtual ICollection<nti_transmittals_file_reports> nti_transmittals_file_reports { get; set; }
    }
}
