//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class nti_transmittals_file_reports
    {
        public nti_transmittals_file_reports()
        {
            this.nti_transmittals_file_report_ratings = new HashSet<nti_transmittals_file_report_ratings>();
        }
    
        public int id { get; set; }
        public int nti_transmittals_file_id { get; set; }
        public System.DateTime date { get; set; }
        public string advertiser { get; set; }
        public string report_name { get; set; }
        public int program_id { get; set; }
        public string stream { get; set; }
        public string program_type { get; set; }
        public int program_duration { get; set; }
        public int stations { get; set; }
        public int CVG { get; set; }
        public int TbyC { get; set; }
        public double TA { get; set; }
        public System.DateTime week_ending { get; set; }
    
        public virtual ICollection<nti_transmittals_file_report_ratings> nti_transmittals_file_report_ratings { get; set; }
        public virtual nti_transmittals_files nti_transmittals_files { get; set; }
    }
}
