//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class nti_to_nsi_conversion_rates
    {
        public int id { get; set; }
        public double conversion_rate { get; set; }
        public int daypart_default_id { get; set; }
        public int media_month_id { get; set; }
    
        public virtual daypart_defaults daypart_defaults { get; set; }
        public virtual media_months media_months { get; set; }
    }
}
