//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class open_market_pricing_guide
    {
        public int id { get; set; }
        public int proposal_version_detail_id { get; set; }
        public short market_code { get; set; }
        public short station_code { get; set; }
        public int station_inventory_manifest_dayparts_id { get; set; }
        public decimal blended_cpm { get; set; }
        public int spots { get; set; }
        public double impressions_per_spot { get; set; }
        public double impressions { get; set; }
        public decimal cost_per_spot { get; set; }
        public decimal cost { get; set; }
        public double station_impressions { get; set; }
    
        public virtual market market { get; set; }
        public virtual proposal_version_details proposal_version_details { get; set; }
        public virtual station station { get; set; }
        public virtual station_inventory_manifest_dayparts station_inventory_manifest_dayparts { get; set; }
    }
}
