//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_version_pricing_inventory_source_type_percentages
    {
        public int id { get; set; }
        public int plan_version_pricing_execution_id { get; set; }
        public byte inventory_source_type { get; set; }
        public int percentage { get; set; }
    
        public virtual plan_version_pricing_executions plan_version_pricing_executions { get; set; }
    }
}
