//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_version_weekly_breakdown
    {
        public int id { get; set; }
        public int media_week_id { get; set; }
        public int number_active_days { get; set; }
        public string active_days_label { get; set; }
        public double impressions { get; set; }
        public double impressions_percentage { get; set; }
        public int plan_version_id { get; set; }
        public double rating_points { get; set; }
        public decimal budget { get; set; }
        public Nullable<int> spot_length_id { get; set; }
        public Nullable<int> standard_daypart_id { get; set; }
        public Nullable<double> percentage_of_week { get; set; }
        public double adu_impressions { get; set; }
        public Nullable<double> unit_impressions { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<int> custom_daypart_organization_id { get; set; }
        public string custom_daypart_name { get; set; }
        public Nullable<int> plan_version_daypart_id { get; set; }
    
        public virtual media_weeks media_weeks { get; set; }
        public virtual spot_lengths spot_lengths { get; set; }
        public virtual standard_dayparts standard_dayparts { get; set; }
        public virtual plan_versions plan_versions { get; set; }
        public virtual plan_version_dayparts plan_version_dayparts { get; set; }
    }
}
