//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_version_custom_dayparts
    {
        public int id { get; set; }
        public int custom_daypart_organization_id { get; set; }
        public string custom_daypart_name { get; set; }
        public int start_time_seconds { get; set; }
        public int end_time_seconds { get; set; }
        public Nullable<double> weighting_goal_percent { get; set; }
        public int daypart_type { get; set; }
        public bool is_start_time_modified { get; set; }
        public bool is_end_time_modified { get; set; }
        public int plan_version_id { get; set; }
        public Nullable<int> show_type_restrictions_contain_type { get; set; }
        public Nullable<int> genre_restrictions_contain_type { get; set; }
        public Nullable<int> program_restrictions_contain_type { get; set; }
        public Nullable<int> affiliate_restrictions_contain_type { get; set; }
        public Nullable<double> weekdays_weighting { get; set; }
        public Nullable<double> weekend_weighting { get; set; }
    
        public virtual custom_daypart_organizations custom_daypart_organizations { get; set; }
    }
}
