//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_version_buying_parameters_inventory_source_percentages
    {
        public int id { get; set; }
        public int plan_version_buying_parameter_id { get; set; }
        public int inventory_source_id { get; set; }
        public int percentage { get; set; }
    
        public virtual inventory_sources inventory_sources { get; set; }
        public virtual plan_version_buying_parameters plan_version_buying_parameters { get; set; }
    }
}
