//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_version_daypart_goals
    {
        public plan_version_daypart_goals()
        {
            this.plan_version_daypart_available_markets = new HashSet<plan_version_daypart_available_markets>();
            this.plan_version_daypart_flight_days = new HashSet<plan_version_daypart_flight_days>();
            this.plan_version_daypart_flight_hiatus_days = new HashSet<plan_version_daypart_flight_hiatus_days>();
            this.plan_version_daypart_weekly_breakdown = new HashSet<plan_version_daypart_weekly_breakdown>();
        }
    
        public int id { get; set; }
        public int plan_version_daypart_id { get; set; }
        public System.DateTime flight_start_Date { get; set; }
        public System.DateTime flight_end_Date { get; set; }
        public decimal budget { get; set; }
        public double target_impression { get; set; }
        public decimal target_cpm { get; set; }
        public double target_rating_points { get; set; }
        public decimal target_cpp { get; set; }
        public double target_universe { get; set; }
        public double hh_impressions { get; set; }
        public decimal hh_cpm { get; set; }
        public double hh_rating_points { get; set; }
        public decimal hh_cpp { get; set; }
        public double hh_universe { get; set; }
        public int currency { get; set; }
        public double coverage_goal_percent { get; set; }
        public int goal_breakdown_type { get; set; }
        public bool is_adu_enabled { get; set; }
        public Nullable<double> impressions_per_unit { get; set; }
    
        public virtual ICollection<plan_version_daypart_available_markets> plan_version_daypart_available_markets { get; set; }
        public virtual ICollection<plan_version_daypart_flight_days> plan_version_daypart_flight_days { get; set; }
        public virtual ICollection<plan_version_daypart_flight_hiatus_days> plan_version_daypart_flight_hiatus_days { get; set; }
        public virtual plan_version_dayparts plan_version_dayparts { get; set; }
        public virtual ICollection<plan_version_daypart_weekly_breakdown> plan_version_daypart_weekly_breakdown { get; set; }
    }
}
