//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_version_daypart_program_restrictions
    {
        public int id { get; set; }
        public int plan_version_daypart_id { get; set; }
        public string program_name { get; set; }
        public Nullable<int> genre_id { get; set; }
        public string content_rating { get; set; }
    
        public virtual genre genre { get; set; }
        public virtual plan_version_dayparts plan_version_dayparts { get; set; }
    }
}
