//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_flight
    {
        public plan_flight()
        {
            this.plan_flight_hiatus = new HashSet<plan_flight_hiatus>();
        }
    
        public int id { get; set; }
        public int plan_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string notes { get; set; }
    
        public virtual ICollection<plan_flight_hiatus> plan_flight_hiatus { get; set; }
        public virtual plan plan { get; set; }
    }
}
