//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_version_daypart_audience_vpvhs
    {
        public int id { get; set; }
        public int plan_version_daypart_id { get; set; }
        public int audience_id { get; set; }
        public int standard_daypart_id { get; set; }
        public int vpvh_type { get; set; }
        public double vpvh_value { get; set; }
        public System.DateTime starting_point { get; set; }
    
        public virtual audience audience { get; set; }
        public virtual plan_version_dayparts plan_version_dayparts { get; set; }
        public virtual standard_dayparts standard_dayparts { get; set; }
    }
}
