//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_version_dayparts
    {
        public plan_version_dayparts()
        {
            this.plan_version_daypart_genre_restrictions = new HashSet<plan_version_daypart_genre_restrictions>();
            this.plan_version_daypart_program_restrictions = new HashSet<plan_version_daypart_program_restrictions>();
            this.plan_version_daypart_show_type_restrictions = new HashSet<plan_version_daypart_show_type_restrictions>();
            this.plan_version_daypart_affiliate_restrictions = new HashSet<plan_version_daypart_affiliate_restrictions>();
        }
    
        public int id { get; set; }
        public int daypart_code_id { get; set; }
        public int start_time_seconds { get; set; }
        public int end_time_seconds { get; set; }
        public Nullable<double> weighting_goal_percent { get; set; }
        public int daypart_type { get; set; }
        public bool is_start_time_modified { get; set; }
        public bool is_end_time_modified { get; set; }
        public int plan_version_id { get; set; }
        public Nullable<int> show_type_restrictions_contain_type { get; set; }
        public Nullable<int> genre_restrictions_contain_type { get; set; }
        public Nullable<int> program_restrictions_contain_type { get; set; }
        public Nullable<int> affiliate_restrictions_contain_type { get; set; }
    
        public virtual ICollection<plan_version_daypart_genre_restrictions> plan_version_daypart_genre_restrictions { get; set; }
        public virtual ICollection<plan_version_daypart_program_restrictions> plan_version_daypart_program_restrictions { get; set; }
        public virtual ICollection<plan_version_daypart_show_type_restrictions> plan_version_daypart_show_type_restrictions { get; set; }
        public virtual plan_versions plan_versions { get; set; }
        public virtual daypart_codes daypart_codes { get; set; }
        public virtual ICollection<plan_version_daypart_affiliate_restrictions> plan_version_daypart_affiliate_restrictions { get; set; }
    }
}
