//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class postlog_files
    {
        public postlog_files()
        {
            this.postlog_file_problems = new HashSet<postlog_file_problems>();
            this.postlog_file_details = new HashSet<postlog_file_details>();
        }
    
        public int id { get; set; }
        public string file_name { get; set; }
        public string file_hash { get; set; }
        public int source_id { get; set; }
        public System.DateTime created_date { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<postlog_file_problems> postlog_file_problems { get; set; }
        public virtual ICollection<postlog_file_details> postlog_file_details { get; set; }
    }
}
