//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_file_details
    {
        public post_file_details()
        {
            this.post_file_detail_impressions = new HashSet<post_file_detail_impressions>();
        }
    
        public int id { get; set; }
        public int post_file_id { get; set; }
        public Nullable<int> rank { get; set; }
        public string market { get; set; }
        public string station { get; set; }
        public string affiliate { get; set; }
        public System.DateTime weekstart { get; set; }
        public string day { get; set; }
        public System.DateTime date { get; set; }
        public int time_aired { get; set; }
        public string program_name { get; set; }
        public int spot_length { get; set; }
        public int spot_length_id { get; set; }
        public string house_isci { get; set; }
        public string client_isci { get; set; }
        public string advertiser { get; set; }
        public string inventory_source { get; set; }
        public string inventory_source_daypart { get; set; }
        public string inventory_out_of_spec_reason { get; set; }
        public int estimate_id { get; set; }
        public string detected_via { get; set; }
        public int spot { get; set; }
    
        public virtual ICollection<post_file_detail_impressions> post_file_detail_impressions { get; set; }
        public virtual post_files post_files { get; set; }
        public virtual spot_lengths spot_lengths { get; set; }
    }
}
