//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class proposal_buy_file_detail_audiences
    {
        public int id { get; set; }
        public int proposal_buy_file_detail_id { get; set; }
        public int audience_id { get; set; }
        public int audience_rank { get; set; }
        public int audience_population { get; set; }
        public double impressions { get; set; }
    
        public virtual audience audience { get; set; }
        public virtual proposal_buy_file_details proposal_buy_file_details { get; set; }
    }
}
