//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class proposal_buy_file_details
    {
        public proposal_buy_file_details()
        {
            this.proposal_buy_file_detail_audiences = new HashSet<proposal_buy_file_detail_audiences>();
            this.proposal_buy_file_detail_weeks = new HashSet<proposal_buy_file_detail_weeks>();
        }
    
        public int id { get; set; }
        public int proposal_buy_file_id { get; set; }
        public int total_spots { get; set; }
        public decimal spot_cost { get; set; }
        public decimal total_cost { get; set; }
        public int spot_length_id { get; set; }
        public int daypart_id { get; set; }
        public int station_id { get; set; }
    
        public virtual daypart daypart { get; set; }
        public virtual ICollection<proposal_buy_file_detail_audiences> proposal_buy_file_detail_audiences { get; set; }
        public virtual ICollection<proposal_buy_file_detail_weeks> proposal_buy_file_detail_weeks { get; set; }
        public virtual proposal_buy_files proposal_buy_files { get; set; }
        public virtual spot_lengths spot_lengths { get; set; }
        public virtual station station { get; set; }
    }
}
