//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class proposal
    {
        public proposal()
        {
            this.proposal_versions = new HashSet<proposal_versions>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int advertiser_id { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public int primary_version_id { get; set; }
        public Nullable<int> campaign_id { get; set; }
    
        public virtual ICollection<proposal_versions> proposal_versions { get; set; }
    }
}
