//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class proposal_buy_file_detail_weeks
    {
        public int id { get; set; }
        public int proposal_buy_file_detail_id { get; set; }
        public int media_week_id { get; set; }
        public int spots { get; set; }
    
        public virtual media_weeks media_weeks { get; set; }
        public virtual proposal_buy_file_details proposal_buy_file_details { get; set; }
    }
}
