//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class proposal_version_detail_proprietary_pricing
    {
        public int proposal_version_detail_id { get; set; }
        public byte inventory_source { get; set; }
        public double impressions_balance { get; set; }
        public decimal cpm { get; set; }
    
        public virtual proposal_version_details proposal_version_details { get; set; }
    }
}
