//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class proposal_buy_files
    {
        public proposal_buy_files()
        {
            this.proposal_buy_file_details = new HashSet<proposal_buy_file_details>();
        }
    
        public int id { get; set; }
        public string file_name { get; set; }
        public string file_hash { get; set; }
        public Nullable<int> estimate_id { get; set; }
        public int proposal_version_detail_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_date { get; set; }
    
        public virtual ICollection<proposal_buy_file_details> proposal_buy_file_details { get; set; }
        public virtual proposal_version_details proposal_version_details { get; set; }
    }
}
