//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate_files
    {
        public rate_files()
        {
            this.station_contacts = new HashSet<station_contacts>();
            this.station_contacts1 = new HashSet<station_contacts>();
            this.station_programs = new HashSet<station_programs>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string identifier { get; set; }
        public string file_hash { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public byte status { get; set; }
        public byte rate_source { get; set; }
        public Nullable<int> sweep_book_id { get; set; }
        public Nullable<byte> play_back_type { get; set; }
    
        public virtual ICollection<station_contacts> station_contacts { get; set; }
        public virtual ICollection<station_contacts> station_contacts1 { get; set; }
        public virtual ICollection<station_programs> station_programs { get; set; }
        public virtual media_months media_months { get; set; }
    }
}
