//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating_adjustments
    {
        public int media_month_id { get; set; }
        public decimal annual_adjustment { get; set; }
        public decimal nti_adjustment { get; set; }
    
        public virtual media_months media_months { get; set; }
    }
}
