//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class reel_isci_advertiser_name_references
    {
        public int id { get; set; }
        public int reel_isci_id { get; set; }
        public string advertiser_name_reference { get; set; }
    
        public virtual reel_iscis reel_iscis { get; set; }
    }
}
