//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class scx_generation_open_market_job_markets
    {
        public int id { get; set; }
        public int scx_generation_open_market_job_id { get; set; }
        public int rank { get; set; }
    
        public virtual scx_generation_open_market_jobs scx_generation_open_market_jobs { get; set; }
    }
}
