//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class spot_exceptions_recommended_plan_decision
    {
        public int id { get; set; }
        public int spot_exceptions_recommended_plan_detail_id { get; set; }
        public string username { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual spot_exceptions_recommended_plan_details spot_exceptions_recommended_plan_details { get; set; }
    }
}
