//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class spot_exceptions_recommended_plan_details
    {
        public spot_exceptions_recommended_plan_details()
        {
            this.spot_exceptions_recommended_plan_decision = new HashSet<spot_exceptions_recommended_plan_decision>();
        }
    
        public int id { get; set; }
        public int spot_exceptions_recommended_plan_id { get; set; }
        public int recommended_plan_id { get; set; }
        public double metric_percent { get; set; }
    
        public virtual plan plan { get; set; }
        public virtual ICollection<spot_exceptions_recommended_plan_decision> spot_exceptions_recommended_plan_decision { get; set; }
        public virtual spot_exceptions_recommended_plans spot_exceptions_recommended_plans { get; set; }
    }
}
