//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_inventory_spots
    {
        public station_inventory_spots()
        {
            this.station_inventory_spot_audiences = new HashSet<station_inventory_spot_audiences>();
        }
    
        public int id { get; set; }
        public Nullable<int> proposal_version_detail_quarter_week_id { get; set; }
        public int station_inventory_manifest_id { get; set; }
        public int media_week_id { get; set; }
        public bool inventory_lost { get; set; }
        public Nullable<double> overridden_impressions { get; set; }
        public Nullable<decimal> overridden_rate { get; set; }
        public Nullable<decimal> delivery_cpm { get; set; }
    
        public virtual proposal_version_detail_quarter_weeks proposal_version_detail_quarter_weeks { get; set; }
        public virtual station_inventory_manifest station_inventory_manifest { get; set; }
        public virtual ICollection<station_inventory_spot_audiences> station_inventory_spot_audiences { get; set; }
    }
}
