//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_contacts
    {
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public byte type { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<int> created_file_id { get; set; }
        public string company { get; set; }
        public Nullable<int> modified_file_id { get; set; }
        public int station_id { get; set; }
    
        public virtual inventory_files inventory_files { get; set; }
        public virtual inventory_files inventory_files1 { get; set; }
        public virtual station station { get; set; }
    }
}
