//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_inventory_manifest_daypart_genres
    {
        public int id { get; set; }
        public int station_inventory_manifest_daypart_id { get; set; }
        public int genre_id { get; set; }
    
        public virtual station_inventory_manifest_dayparts station_inventory_manifest_dayparts { get; set; }
        public virtual genre genre { get; set; }
    }
}
