//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_program_flight_audiences
    {
        public int station_program_flight_id { get; set; }
        public int audience_id { get; set; }
        public Nullable<double> impressions { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<decimal> cpm15 { get; set; }
        public Nullable<decimal> cpm30 { get; set; }
        public Nullable<decimal> cpm60 { get; set; }
        public Nullable<decimal> cpm90 { get; set; }
        public Nullable<decimal> cpm120 { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_date { get; set; }
    
        public virtual station_program_flights station_program_flights { get; set; }
    }
}
