//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_component_parameters
    {
        public string component_id { get; set; }
        public string parameter_key { get; set; }
        public string parameter_value { get; set; }
        public string parameter_type { get; set; }
        public string description { get; set; }
        public System.DateTime last_modified_time { get; set; }
    }
}
