//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMapping.Broadcast
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ccc_daypart
    {
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public int tier { get; set; }
        public int start_time { get; set; }
        public int end_time { get; set; }
        public Nullable<int> mon { get; set; }
        public Nullable<int> tue { get; set; }
        public Nullable<int> wed { get; set; }
        public Nullable<int> thu { get; set; }
        public Nullable<int> fri { get; set; }
        public Nullable<int> sat { get; set; }
        public Nullable<int> sun { get; set; }
        public string daypart_text { get; set; }
        public double total_hours { get; set; }
    }
}
