CREATE TABLE [dbo].[affidavits_staging] (
    [id]                  BIGINT       IDENTITY (1, 1) NOT NULL,
    [media_month_id]      INT          NOT NULL,
    [status_id]           TINYINT      NOT NULL,
    [invoice_id]          INT          NOT NULL,
    [traffic_id]          INT          NULL,
    [material_id]         INT          NULL,
    [zone_id]             INT          NULL,
    [network_id]          INT          NULL,
    [spot_length_id]      TINYINT      NULL,
    [air_date]            DATETIME     NULL,
    [air_time]            INT          NULL,
    [rate]                INT          NULL,
    [affidavit_file_line] INT          NOT NULL,
    [affidavit_air_date]  VARCHAR (31) NOT NULL,
    [affidavit_air_time]  VARCHAR (31) NOT NULL,
    [affidavit_length]    VARCHAR (15) NOT NULL,
    [affidavit_copy]      VARCHAR (63) NOT NULL,
    [affidavit_net]       VARCHAR (15) NOT NULL,
    [affidavit_syscode]   VARCHAR (15) NOT NULL,
    [affidavit_rate]      VARCHAR (15) NOT NULL,
    [hash]                CHAR (59)    NULL,
    [subscribers]         INT          NULL,
    [program_name]        VARCHAR (63) CONSTRAINT [DF_affidavits_staging_program_name] DEFAULT ('') NOT NULL,
    [adjusted_air_date]   DATE         NULL,
    [adjusted_air_time]   INT          NULL,
    CONSTRAINT [PK_affidavits_staging] PRIMARY KEY CLUSTERED ([media_month_id] ASC, [id] ASC) WITH (FILLFACTOR = 90) ON [MediaMonthScheme] ([media_month_id])
);

