/* import { createAction } from "Utils/action-creator";

const ROOT = "post-pre-posting";

export const POST_PRE_POSTING_INITIALDATA = createAction(
  `${ROOT}/POST_PRE_POSTING_INITIALDATA`
);
export const POST_PRE_POSTING = createAction(`${ROOT}/POST_PRE_POSTING`);
export const FILTERED_POST_PRE_POSTING = createAction(
  `${ROOT}/FILTERED_POST_PRE_POSTING`
);
export const DELETE_POST_PRE_POSTING = createAction(
  `${ROOT}/DELETE_POST_PRE_POSTING`
);
export const POST_PRE_POSTING_FILE_EDIT = createAction(
  `${ROOT}/POST_PRE_POSTING_FILE_EDIT`
);
export const POST_PRE_POSTING_FILE_SAVE = createAction(
  `${ROOT}/POST_PRE_POSTING_FILE_SAVE`
);
export const POST_PRE_POSTING_FILE_UPLOAD = createAction(
  `${ROOT}/POST_PRE_POSTING_FILE_UPLOAD`
);

export const TOGGLE_MODAL = `${ROOT}/TOGGLE_MODAL`;

export const FILE_EDIT_FORM_UPDATE_EQUIVALIZED = `${ROOT}/FILE_EDIT_FORM_UPDATE_EQUIVALIZED`;
export const FILE_EDIT_FORM_UPDATE_POSTING_BOOK = `${ROOT}/FILE_EDIT_FORM_UPDATE_POSTING_BOOK`;
export const FILE_EDIT_FORM_UPDATE_PLAYBACK_TYPE = `${ROOT}/FILE_EDIT_FORM_UPDATE_PLAYBACK_TYPE`;
export const FILE_EDIT_FORM_UPDATE_DEMOS = `${ROOT}/FILE_EDIT_FORM_UPDATE_DEMOS`;

export const FILE_UPLOAD_FORM_UPDATE_EQUIVALIZED = `${ROOT}/FILE_UPLOAD_FORM_UPDATE_EQUIVALIZED`;
export const FILE_UPLOAD_FORM_UPDATE_POSTING_BOOK = `${ROOT}/FILE_UPLOAD_FORM_UPDATE_POSTING_BOOK`;
export const FILE_UPLOAD_FORM_UPDATE_PLAYBACK_TYPE = `${ROOT}/FILE_UPLOAD_FORM_UPDATE_PLAYBACK_TYPE`;
export const FILE_UPLOAD_FORM_UPDATE_DEMOS = `${ROOT}/FILE_UPLOAD_FORM_UPDATE_DEMOS`;
export const CLEAR_FILE_UPLOAD_FORM = `${ROOT}/CLEAR_FILE_UPLOAD_FORM`; */

export const REQUEST_ENVIRONMENT = "app/REQUEST_ENVIRONMENT";
export const RECEIVE_ENVIRONMENT = "app/RECEIVE_ENVIRONMENT";

export const REQUEST_EMPLOYEE = "app/REQUEST_EMPLOYEE";
export const RECEIVE_EMPLOYEE = "app/RECEIVE_EMPLOYEE";

export const TOGGLE_MODAL = "app/TOGGLE_MODAL";

export const DEPLOY_ERROR = "app/DEPLOY_ERROR";
export const CLEAR_ERRORS = "app/CLEAR_ERRORS";

export const CREATE_ALERT = "app/CREATE_ALERT";

export const SET_OVERLAY_LOADING = "app/SET_OVERLAY_LOADING";
export const SET_OVERLAY_PROCESSING = "app/SET_OVERLAY_PROCESSING";

export const STORE_FILE = "app/STORE_FILE";
export const READ_FILE_B64 = "app/READ_FILE_B64";
export const STORE_FILE_B64 = "app/STORE_FILE_B64";
export const CLEAR_FILE = "app/CLEAR_FILE";

export const TOGGLE_DISABLED_DROPZONES = "app/TOGGLE_DISABLED_DROPZONES";
