export const REQUEST_POST_INITIALDATA = 'REQUEST_POST_INITIALDATA';
export const RECEIVE_POST_INITIALDATA = 'RECEIVE_POST_INITIALDATA';

export const REQUEST_POST = 'REQUEST_POST';
export const RECEIVE_POST = 'RECEIVE_POST';

export const REQUEST_POST_FILE_EDIT = 'REQUEST_POST_FILE_EDIT';
export const RECEIVE_POST_FILE_EDIT = 'RECEIVE_POST_FILE_EDIT';

export const REQUEST_POST_FILE_EDIT_SAVE = 'REQUEST_POST_FILE_EDIT_SAVE';
export const RECEIVE_POST_FILE_EDIT_SAVE = 'RECEIVE_POST_FILE_EDIT_SAVE';

export const REQUEST_ASSIGN_POST_DISPLAY = 'REQUEST_ASSIGN_POST_DISPLAY';
export const ASSIGN_POST_DISPLAY = 'ASSIGN_POST_DISPLAY';

export const REQUEST_FILTERED_POST = 'REQUEST_FILTERED_POST';
export const RECEIVE_FILTERED_POST = 'RECEIVE_FILTERED_POST';
export const RECEIVE_FILTERED_POST_ERROR = 'RECEIVE_FILTERED_POST_ERROR';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const FILE_EDIT_FORM_UPDATE_EQUIVALIZED = 'FILE_EDIT_FORM_UPDATE_EQUIVALIZED';
export const FILE_EDIT_FORM_UPDATE_POSTING_BOOK = 'FILE_EDIT_FORM_UPDATE_POSTING_BOOK';
export const FILE_EDIT_FORM_UPDATE_PLAYBACK_TYPE = 'FILE_EDIT_FORM_UPDATE_PLAYBACK_TYPE';
export const FILE_EDIT_FORM_UPDATE_DEMOS = 'FILE_EDIT_FORM_UPDATE_DEMOS';

export const FILE_UPLOAD_FORM_UPDATE_EQUIVALIZED = 'FILE_UPLOAD_FORM_UPDATE_EQUIVALIZED';
export const FILE_UPLOAD_FORM_UPDATE_POSTING_BOOK = 'FILE_UPLOAD_FORM_UPDATE_POSTING_BOOK';
export const FILE_UPLOAD_FORM_UPDATE_PLAYBACK_TYPE = 'FILE_UPLOAD_FORM_UPDATE_PLAYBACK_TYPE';
export const FILE_UPLOAD_FORM_UPDATE_DEMOS = 'FILE_UPLOAD_FORM_UPDATE_DEMOS';
export const CLEAR_FILE_UPLOAD_FORM = 'CLEAR_FILE_UPLOAD_FORM';

export const REQUEST_POST_FILE_UPLOAD = 'REQUEST_POST_FILE_UPLOAD';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_RESPONSE = 'DELETE_POST_FAILURE';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

