import { createAction } from "../actionCreator";

export const ARCHIVE_UNLIKED_ISCI = createAction("post/ARCHIVE_UNLIKED_ISCI");
export const UNLINKED_ISCIS_DATA = createAction("post/UNLINKED_ISCIS_DATA");
export const LOAD_ARCHIVED_ISCI = createAction("post/LOAD_ARCHIVED_ISCI");
export const LOAD_VALID_ISCI = createAction("post/LOAD_VALID_ISCI");
export const RESCRUB_UNLIKED_ISCI = createAction("post/RESCRUB_UNLIKED_ISCI");
export const MAP_UNLINKED_ISCI = createAction("post/MAP_UNLINKED_ISCI");
export const UNDO_ARCHIVED_ISCI = createAction("post/UNDO_ARCHIVED_ISCI");
export const UNDO_SCRUB_STATUS = createAction("post/UNDO_SCRUB_STATUS");
export const PROCESS_NTI_FILE = createAction("post/PROCESS_NTI_FILE");

export const REQUEST_CLEAR_FILTERED_SCRUBBING_DATA =
  "post/REQUEST_CLEAR_FILTERED_SCRUBBING_DATA";
export const RECEIVE_CLEAR_FILTERED_SCRUBBING_DATA =
  "post/RECEIVE_CLEAR_FILTERED_SCRUBBING_DATA";
export const CLEAR_FILTERED_SCRUBBING_DATA =
  "post/CLEAR_FILTERED_SCRUBBING_DATA";

export const SAVE_NEW_CLIENT_SCRUBS = "post/SAVE_NEW_CLIENT_SCRUBS";
export const CLOSE_UNLINKED_ISCI_MODAL = "post/CLOSE_UNLINKED_ISCI_MODAL";

export const REQUEST_POST = "post/REQUEST_POST";
export const RECEIVE_POST = "post/RECEIVE_POST";

export const REQUEST_ASSIGN_POST_DISPLAY = "post/REQUEST_ASSIGN_POST_DISPLAY";
export const ASSIGN_POST_DISPLAY = "post/ASSIGN_POST_DISPLAY";

export const REQUEST_FILTERED_POST = "post/REQUEST_FILTERED_POST";
export const RECEIVE_FILTERED_POST = "post/RECEIVE_FILTERED_POST";

export const REQUEST_FILTERED_UNLINKED = "post/REQUEST_FILTERED_UNLINKED";
export const RECEIVE_FILTERED_UNLINKED = "post/RECEIVE_FILTERED_UNLINKED";

export const REQUEST_FILTERED_ARCHIVED = "post/REQUEST_FILTERED_ARCHIVED";
export const RECEIVE_FILTERED_ARCHIVED = "post/RECEIVE_FILTERED_ARCHIVED";

export const RECEIVE_CLEAR_ISCI_FILTER = "post/RECEIVE_CLEAR_ISCI_FILTER";

export const REQUEST_POST_CLIENT_SCRUBBING =
  "post/REQUEST_POST_CLIENT_SCRUBBING";
export const RECEIVE_POST_CLIENT_SCRUBBING =
  "post/RECEIVE_POST_CLIENT_SCRUBBING";

export const REQUEST_FILTERED_SCRUBBING_DATA =
  "post/REQUEST_FILTERED_SCRUBBING_DATA";
export const RECEIVE_FILTERED_SCRUBBING_DATA =
  "post/RECEIVE_FILTERED_SCRUBBING_DATA";
export const REQUEST_CLEAR_SCRUBBING_FILTERS_LIST =
  "post/REQUEST_CLEAR_SCRUBBING_FILTERS_LIST";
export const RECEIVE_CLEAR_SCRUBBING_FILTERS_LIST =
  "post/RECEIVE_CLEAR_SCRUBBING_FILTERS_LIST";

export const REQUEST_UNLINKED_ISCIS_DATA = "post/REQUEST_UNLINKED_ISCIS_DATA";
export const RECEIVE_UNLINKED_ISCIS_DATA = "post/RECEIVE_UNLINKED_ISCIS_DATA";

export const REQUEST_POST_OVERRIDE_STATUS = "post/REQUEST_POST_OVERRIDE_STATUS";
export const RECEIVE_POST_OVERRIDE_STATUS = "post/RECEIVE_POST_OVERRIDE_STATUS";

export const REQUEST_SWAP_PROPOSAL_DETAIL = "post/REQUEST_SWAP_PROPOSAL_DETAIL";
export const RECEIVE_SWAP_PROPOSAL_DETAIL = "post/RECEIVE_SWAP_PROPOSAL_DETAIL";
