import { createAction } from '../actionCreator';

export const ARCHIVE_UNLIKED_ISCI = createAction('ARCHIVE_UNLIKED_ISCI');
export const UNLINKED_ISCIS_DATA = createAction('UNLINKED_ISCIS_DATA');

export const REQUEST_POST = 'REQUEST_POST';
export const RECEIVE_POST = 'RECEIVE_POST';

export const REQUEST_ASSIGN_POST_DISPLAY = 'REQUEST_ASSIGN_POST_DISPLAY';
export const ASSIGN_POST_DISPLAY = 'ASSIGN_POST_DISPLAY';

export const REQUEST_FILTERED_POST = 'REQUEST_FILTERED_POST';
export const RECEIVE_FILTERED_POST = 'RECEIVE_FILTERED_POST';

export const REQUEST_POST_CLIENT_SCRUBBING = 'REQUEST_POST_CLIENT_SCRUBBING';
export const RECEIVE_POST_CLIENT_SCRUBBING = 'RECEIVE_POST_CLIENT_SCRUBBING';

export const REQUEST_FILTERED_SCRUBBING_DATA = 'REQUEST_FILTERED_SCRUBBING_DATA';
export const RECEIVE_FILTERED_SCRUBBING_DATA = 'RECEIVE_FILTERED_SCRUBBING_DATA';
export const REQUEST_CLEAR_SCRUBBING_FILTERS_LIST = 'REQUEST_CLEAR_SCRUBBING_FILTERS_LIST';
export const RECEIVE_CLEAR_SCRUBBING_FILTERS_LIST = 'RECEIVE_CLEAR_SCRUBBING_FILTERS_LIST';
