
-- =============================================
-- Author:		CRUD Creator
-- Create date: 02/16/2017 11:29:08 AM
-- Description:	Auto-generated method to insert a proposals record.
-- =============================================
CREATE PROCEDURE usp_proposals_insert
	@id INT OUTPUT,
	@original_proposal_id INT,
	@version_number INT,
	@name VARCHAR(127),
	@product_id INT,
	@agency_company_id INT,
	@advertiser_company_id INT,
	@default_spot_length_id INT,
	@default_daypart_id INT,
	@start_date DATETIME,
	@end_date DATETIME,
	@guarantee_type TINYINT,
	@proposal_type_id INT,
	@proposal_status_id INT,
	@rate_card_type_id INT,
	@traffic_notes TEXT,
	@budget MONEY,
	@is_equivalized BIT,
	@is_audience_deficiency_unit_schedule BIT,
	@include_on_availability_planner BIT,
	@multiple_dayparts BIT,
	@multiple_flights BIT,
	@multiple_spot_lengths BIT,
	@base_ratings_media_month_id INT,
	@base_universe_media_month_id INT,
	@flight_text VARCHAR(1027),
	@optimization_goal TINYINT,
	@optimization_target VARCHAR(15),
	@billing_terms_id INT,
	@additional_information TEXT,
	@salesperson_employee_id INT,
	@date_created DATETIME,
	@date_last_modified DATETIME,
	@network_rate_card_id INT,
	@buyer_note VARCHAR(2047),
	@print_title VARCHAR(2047),
	@include_on_marriage_report BIT,
	@exclude_from_pending_report BIT,
	@posting_media_month_id INT,
	@billing_address_id INT,
	@confirmation_notes VARCHAR(2047),
	@primary_daypart_id INT,
	@is_msa BIT,
	@number_of_materials SMALLINT,
	@total_spots INT,
	@total_gross_cost MONEY,
	@is_upfront BIT,
	@rating_source_id TINYINT,
	@local_pods_authorized BIT,
	@posting_notes VARCHAR(2047),
	@media_plan_format_code TINYINT,
	@finance_notes VARCHAR(2047),
	@billing_notes VARCHAR(2047),
	@media_plan_notes VARCHAR(2047),
	@invoice_format_code TINYINT,
	@is_invoice_weekly_gross_split_required BIT,
	@are_iscis_required_on_invoice BIT,
	@billing_flow_chart_code TINYINT,
	@category_id INT,
	@is_media_ocean_plan BIT,
	@is_cash_back BIT,
	@total_gross_cost_after_cash_back MONEY,
	@campaign_id INT,
	@sales_office_id INT,
	@advertiser_industry_id INT,
	@audience_deficiency_unit_for VARCHAR(31),
	@is_overnight BIT,
	@is_advanced_tv BIT
AS
BEGIN
	INSERT INTO [dbo].[proposals]
	(
		[original_proposal_id],
		[version_number],
		[name],
		[product_id],
		[agency_company_id],
		[advertiser_company_id],
		[default_spot_length_id],
		[default_daypart_id],
		[start_date],
		[end_date],
		[guarantee_type],
		[proposal_type_id],
		[proposal_status_id],
		[rate_card_type_id],
		[traffic_notes],
		[budget],
		[is_equivalized],
		[is_audience_deficiency_unit_schedule],
		[include_on_availability_planner],
		[multiple_dayparts],
		[multiple_flights],
		[multiple_spot_lengths],
		[base_ratings_media_month_id],
		[base_universe_media_month_id],
		[flight_text],
		[optimization_goal],
		[optimization_target],
		[billing_terms_id],
		[additional_information],
		[salesperson_employee_id],
		[date_created],
		[date_last_modified],
		[network_rate_card_id],
		[buyer_note],
		[print_title],
		[include_on_marriage_report],
		[exclude_from_pending_report],
		[posting_media_month_id],
		[billing_address_id],
		[confirmation_notes],
		[primary_daypart_id],
		[is_msa],
		[number_of_materials],
		[total_spots],
		[total_gross_cost],
		[is_upfront],
		[rating_source_id],
		[local_pods_authorized],
		[posting_notes],
		[media_plan_format_code],
		[finance_notes],
		[billing_notes],
		[media_plan_notes],
		[invoice_format_code],
		[is_invoice_weekly_gross_split_required],
		[are_iscis_required_on_invoice],
		[billing_flow_chart_code],
		[category_id],
		[is_media_ocean_plan],
		[is_cash_back],
		[total_gross_cost_after_cash_back],
		[campaign_id],
		[sales_office_id],
		[advertiser_industry_id],
		[audience_deficiency_unit_for],
		[is_overnight],
		[is_advanced_tv]
	)
	VALUES
	(
		@original_proposal_id,
		@version_number,
		@name,
		@product_id,
		@agency_company_id,
		@advertiser_company_id,
		@default_spot_length_id,
		@default_daypart_id,
		@start_date,
		@end_date,
		@guarantee_type,
		@proposal_type_id,
		@proposal_status_id,
		@rate_card_type_id,
		@traffic_notes,
		@budget,
		@is_equivalized,
		@is_audience_deficiency_unit_schedule,
		@include_on_availability_planner,
		@multiple_dayparts,
		@multiple_flights,
		@multiple_spot_lengths,
		@base_ratings_media_month_id,
		@base_universe_media_month_id,
		@flight_text,
		@optimization_goal,
		@optimization_target,
		@billing_terms_id,
		@additional_information,
		@salesperson_employee_id,
		@date_created,
		@date_last_modified,
		@network_rate_card_id,
		@buyer_note,
		@print_title,
		@include_on_marriage_report,
		@exclude_from_pending_report,
		@posting_media_month_id,
		@billing_address_id,
		@confirmation_notes,
		@primary_daypart_id,
		@is_msa,
		@number_of_materials,
		@total_spots,
		@total_gross_cost,
		@is_upfront,
		@rating_source_id,
		@local_pods_authorized,
		@posting_notes,
		@media_plan_format_code,
		@finance_notes,
		@billing_notes,
		@media_plan_notes,
		@invoice_format_code,
		@is_invoice_weekly_gross_split_required,
		@are_iscis_required_on_invoice,
		@billing_flow_chart_code,
		@category_id,
		@is_media_ocean_plan,
		@is_cash_back,
		@total_gross_cost_after_cash_back,
		@campaign_id,
		@sales_office_id,
		@advertiser_industry_id,
		@audience_deficiency_unit_for,
		@is_overnight,
		@is_advanced_tv
	)

	SELECT
		@id = SCOPE_IDENTITY()
END
