import { createAction } from "Utils/action-creator";

const ROOT = "tracker";
export const FILE_UPLOAD = createAction(`${ROOT}/FILE_UPLOAD`);
export const ARCHIVE_UNLIKED_ISCI = createAction(
  `${ROOT}/ARCHIVE_UNLIKED_ISCI`
);
export const UNLINKED_ISCIS_DATA = createAction(`${ROOT}/UNLINKED_ISCIS_DATA`);
export const LOAD_ARCHIVED_ISCI = createAction(`${ROOT}/LOAD_ARCHIVED_ISCI`);
export const LOAD_VALID_ISCI = createAction(`${ROOT}/LOAD_VALID_ISCI`);
export const RESCRUB_UNLIKED_ISCI = createAction(
  `${ROOT}/RESCRUB_UNLIKED_ISCI`
);
export const MAP_UNLINKED_ISCI = createAction(`${ROOT}/MAP_UNLINKED_ISCI`);
export const UNDO_ARCHIVED_ISCI = createAction(`${ROOT}/UNDO_ARCHIVED_ISCI`);
export const UNDO_SCRUB_STATUS = createAction(`${ROOT}/UNDO_SCRUB_STATUS`);

export const LOAD_TRACKER = createAction(`${ROOT}/LOAD_TRACKER`);
export const LOAD_TRACKER_CLIENT_SCRUBBING = createAction(
  `${ROOT}/LOAD_TRACKER_CLIENT_SCRUBBING`
);

export const REQUEST_CLEAR_FILTERED_SCRUBBING_DATA = `${ROOT}/REQUEST_CLEAR_FILTERED_SCRUBBING_DATA`;
export const RECEIVE_CLEAR_FILTERED_SCRUBBING_DATA = `${ROOT}/RECEIVE_CLEAR_FILTERED_SCRUBBING_DATA`;
export const CLEAR_FILTERED_SCRUBBING_DATA = `${ROOT}/CLEAR_FILTERED_SCRUBBING_DATA`;

export const SAVE_NEW_CLIENT_SCRUBS = `${ROOT}/SAVE_NEW_CLIENT_SCRUBS`;
export const CLOSE_UNLINKED_ISCI_MODAL = `${ROOT}/CLOSE_UNLINKED_ISCI_MODAL`;

export const REQUEST_ASSIGN_TRACKER_DISPLAY = `${ROOT}/REQUEST_ASSIGN_TRACKER_DISPLAY`;
export const ASSIGN_TRACKER_DISPLAY = `${ROOT}/ASSIGN_TRACKER_DISPLAY`;

export const REQUEST_FILTERED_TRACKER = `${ROOT}/REQUEST_FILTERED_TRACKER`;
export const RECEIVE_FILTERED_TRACKER = `${ROOT}/RECEIVE_FILTERED_TRACKER`;

export const REQUEST_FILTERED_UNLINKED = `${ROOT}/REQUEST_FILTERED_UNLINKED`;
export const RECEIVE_FILTERED_UNLINKED = `${ROOT}/RECEIVE_FILTERED_UNLINKED`;

export const REQUEST_FILTERED_ARCHIVED = `${ROOT}/REQUEST_FILTERED_ARCHIVED`;
export const RECEIVE_FILTERED_ARCHIVED = `${ROOT}/RECEIVE_FILTERED_ARCHIVED`;

export const RECEIVE_CLEAR_ISCI_FILTER = `${ROOT}/RECEIVE_CLEAR_ISCI_FILTER`;

export const REQUEST_FILTERED_SCRUBBING_DATA = `${ROOT}/REQUEST_FILTERED_SCRUBBING_DATA`;
export const RECEIVE_FILTERED_SCRUBBING_DATA = `${ROOT}/RECEIVE_FILTERED_SCRUBBING_DATA`;
export const REQUEST_CLEAR_SCRUBBING_FILTERS_LIST = `${ROOT}/REQUEST_CLEAR_SCRUBBING_FILTERS_LIST`;
export const RECEIVE_CLEAR_SCRUBBING_FILTERS_LIST = `${ROOT}/RECEIVE_CLEAR_SCRUBBING_FILTERS_LIST`;

export const REQUEST_UNLINKED_ISCIS_DATA = `${ROOT}/REQUEST_UNLINKED_ISCIS_DATA`;
export const RECEIVE_UNLINKED_ISCIS_DATA = `${ROOT}/RECEIVE_UNLINKED_ISCIS_DATA`;

export const REQUEST_TRACKER_OVERRIDE_STATUS = `${ROOT}/REQUEST_TRACKER_OVERRIDE_STATUS`;
export const RECEIVE_TRACKER_OVERRIDE_STATUS = `${ROOT}/RECEIVE_TRACKER_OVERRIDE_STATUS`;

export const REQUEST_SWAP_PROPOSAL_DETAIL = `${ROOT}/REQUEST_SWAP_PROPOSAL_DETAIL`;
export const RECEIVE_SWAP_PROPOSAL_DETAIL = `${ROOT}/RECEIVE_SWAP_PROPOSAL_DETAIL`;
