export const REQUEST_PROPOSAL_INITIALDATA = 'REQUEST_PROPOSAL_INITIALDATA';
export const RECEIVE_PROPOSAL_INITIALDATA = 'RECEIVE_PROPOSAL_INITIALDATA';

export const REQUEST_PROPOSALS = 'REQUEST_PROPOSALS';
export const RECEIVE_PROPOSALS = 'RECEIVE_PROPOSALS';

export const REQUEST_PROPOSAL_LOCK = 'REQUEST_PROPOSAL_LOCK';
export const RECEIVE_PROPOSAL_LOCK = 'RECEIVE_PROPOSAL_LOCK';

export const REQUEST_PROPOSAL_UNLOCK = 'REQUEST_PROPOSAL_UNLOCK';
export const RECEIVE_PROPOSAL_UNLOCK = 'RECEIVE_PROPOSAL_UNLOCK';

export const REQUEST_PROPOSAL = 'REQUEST_PROPOSAL';
export const RECEIVE_PROPOSAL = 'RECEIVE_PROPOSAL';

export const REQUEST_PROPOSAL_VERSIONS = 'REQUEST_PROPOSAL_VERSIONS';
export const RECEIVE_PROPOSAL_VERSIONS = 'RECEIVE_PROPOSAL_VERSIONS';

export const REQUEST_PROPOSAL_VERSION = 'REQUEST_PROPOSAL_VERSION';
export const RECEIVE_PROPOSAL_VERSION = 'RECEIVE_PROPOSAL_VERSION';

export const SAVE_PROPOSAL = 'SAVE_PROPOSAL';
export const SAVE_PROPOSAL_AS_VERSION = 'SAVE_PROPOSAL_AS_VERSION';

export const DELETE_PROPOSAL = 'DELETE_PROPOSAL';

export const UPDATE_PROPOSAL = 'UPDATE_PROPOSAL';
export const RECEIVE_UPDATED_PROPOSAL = 'RECEIVE_UPDATED_PROPOSAL';

export const UPDATE_PROPOSAL_EDIT_FORM = 'UPDATE_PROPOSAL_EDIT_FORM';
export const UPDATE_PROPOSAL_EDIT_FORM_DETAIL = 'UPDATE_PROPOSAL_EDIT_FORM_DETAIL';
export const UPDATE_PROPOSAL_EDIT_FORM_DETAIL_GRID = 'UPDATE_PROPOSAL_EDIT_FORM_DETAIL_GRID';

export const MODEL_NEW_PROPOSAL_DETAIL = 'MODEL_NEW_PROPOSAL_DETAIL';
export const RECEIVE_NEW_PROPOSAL_DETAIL = 'RECEIVE_NEW_PROPOSAL_DETAIL';

export const DELETE_PROPOSAL_DETAIL = 'DELETE_PROPOSAL_DETAIL';

export const FLATTEN_DETAIL = 'FLATTEN_DETAIL';
export const RECEIVE_FLATTEN_DETAIL = 'RECEIVE_FLATTEN_DETAIL';

export const UNORDER_PROPOSAL = 'UNORDER_PROPOSAL';
