CREATE PROCEDURE usp_cmw_traffic_update
(
	@id		Int,
	@agency_cmw_traffic_company_id		Int,
	@advertiser_cmw_traffic_company_id		Int,
	@cmw_traffic_product_id		Int,
	@system_id		Int,
	@zone_id		Int,
	@network_id		Int,
	@status_id		Int,
	@cmw_traffic_product_description_id		Int,
	@coverage_universe		Float,
	@order_date		DateTime,
	@release_name		VarChar(63),
	@release_date		DateTime,
	@start_date		DateTime,
	@end_date		DateTime,
	@notes		VarChar(2047),
	@flight_text		VarChar(1027),
	@network_handles_copy		Bit,
	@date_created		DateTime,
	@date_last_modified		DateTime,
	@salesperson_employee_id		Int,
	@original_cmw_traffic_id		Int,
	@approved_by_employee_id		Int,
	@approved_date		DateTime,
	@cmw_contact_id		Int,
	@internal_notes		VarChar(2047),
	@version_number		TinyInt,
	@original_cmw_traffic_status_id		Int,
	@default_spot_length_id		Int
)
AS
UPDATE cmw_traffic SET
	agency_cmw_traffic_company_id = @agency_cmw_traffic_company_id,
	advertiser_cmw_traffic_company_id = @advertiser_cmw_traffic_company_id,
	cmw_traffic_product_id = @cmw_traffic_product_id,
	system_id = @system_id,
	zone_id = @zone_id,
	network_id = @network_id,
	status_id = @status_id,
	cmw_traffic_product_description_id = @cmw_traffic_product_description_id,
	coverage_universe = @coverage_universe,
	order_date = @order_date,
	release_name = @release_name,
	release_date = @release_date,
	start_date = @start_date,
	end_date = @end_date,
	notes = @notes,
	flight_text = @flight_text,
	network_handles_copy = @network_handles_copy,
	date_created = @date_created,
	date_last_modified = @date_last_modified,
	salesperson_employee_id = @salesperson_employee_id,
	original_cmw_traffic_id = @original_cmw_traffic_id,
	approved_by_employee_id = @approved_by_employee_id,
	approved_date = @approved_date,
	cmw_contact_id = @cmw_contact_id,
	internal_notes = @internal_notes,
	version_number = @version_number,
	original_cmw_traffic_status_id = @original_cmw_traffic_status_id,
	default_spot_length_id = @default_spot_length_id
WHERE
	id = @id

