CREATE PROCEDURE usp_cmw_traffic_insert
(
	@id		Int		OUTPUT,
	@agency_cmw_traffic_company_id		Int,
	@advertiser_cmw_traffic_company_id		Int,
	@cmw_traffic_product_id		Int,
	@system_id		Int,
	@zone_id		Int,
	@network_id		Int,
	@status_id		Int,
	@cmw_traffic_product_description_id		Int,
	@coverage_universe		Float,
	@order_date		DateTime,
	@release_name		VarChar(63),
	@release_date		DateTime,
	@start_date		DateTime,
	@end_date		DateTime,
	@notes		VarChar(2047),
	@flight_text		VarChar(1027),
	@network_handles_copy		Bit,
	@date_created		DateTime,
	@date_last_modified		DateTime,
	@salesperson_employee_id		Int,
	@original_cmw_traffic_id		Int,
	@approved_by_employee_id		Int,
	@approved_date		DateTime,
	@cmw_contact_id		Int,
	@internal_notes		VarChar(2047),
	@version_number		TinyInt,
	@original_cmw_traffic_status_id		Int,
	@default_spot_length_id		Int
)
AS
INSERT INTO cmw_traffic
(
	agency_cmw_traffic_company_id,
	advertiser_cmw_traffic_company_id,
	cmw_traffic_product_id,
	system_id,
	zone_id,
	network_id,
	status_id,
	cmw_traffic_product_description_id,
	coverage_universe,
	order_date,
	release_name,
	release_date,
	start_date,
	end_date,
	notes,
	flight_text,
	network_handles_copy,
	date_created,
	date_last_modified,
	salesperson_employee_id,
	original_cmw_traffic_id,
	approved_by_employee_id,
	approved_date,
	cmw_contact_id,
	internal_notes,
	version_number,
	original_cmw_traffic_status_id,
	default_spot_length_id
)
VALUES
(
	@agency_cmw_traffic_company_id,
	@advertiser_cmw_traffic_company_id,
	@cmw_traffic_product_id,
	@system_id,
	@zone_id,
	@network_id,
	@status_id,
	@cmw_traffic_product_description_id,
	@coverage_universe,
	@order_date,
	@release_name,
	@release_date,
	@start_date,
	@end_date,
	@notes,
	@flight_text,
	@network_handles_copy,
	@date_created,
	@date_last_modified,
	@salesperson_employee_id,
	@original_cmw_traffic_id,
	@approved_by_employee_id,
	@approved_date,
	@cmw_contact_id,
	@internal_notes,
	@version_number,
	@original_cmw_traffic_status_id,
	@default_spot_length_id
)

SELECT
	@id = SCOPE_IDENTITY()

