// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BroadcastTest.Tests.Features.BCOP
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("StationRateXmlImportExistingRates")]
    public partial class StationRateXmlImportExistingRatesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "StationRateXmlImportExistingRates.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "StationRateXmlImportExistingRates", "\tOnce basic XML Import has been verified to be functional by running tests in Sta" +
                    "tionRateXmlImport.feature, \r\n\tlet\'s generate XML files to verify that special ca" +
                    "ses are validated correctly by the UI import parser.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Upload generated XML file that has no rates")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void UploadGeneratedXMLFileThatHasNoRates()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Upload generated XML file that has no rates", new string[] {
                        "ignore"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I am on the Rate Card screen with rate data loaded successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Air Time",
                        "Program",
                        "Genre",
                        "Rate 30",
                        "Rate 15",
                        "HH Impressions",
                        "Rating",
                        "Flight"});
            table1.AddRow(new string[] {
                        "M-F 9AM-10AM",
                        "CRIME WATCH DAILY",
                        "",
                        "$125.00",
                        "-",
                        "5",
                        "0.20",
                        "2016/09/26 - 2016/12/25"});
#line 9
 testRunner.When("I generate new xml file containing the following rates for station \'WPCH-TV 17.1\'" +
                    "", ((string)(null)), table1, "When ");
#line 12
 testRunner.And("Upload is not completed successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "ModalTitle",
                        "Message"});
            table2.AddRow(new string[] {
                        "Error",
                        "Unable to load XML file. The XML file selected has already been loaded."});
#line 13
 testRunner.Then("I receive the following message in the pop up modal dialog", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
