-- =============================================
-- Author:		CRUD Creator
-- Create date: 04/13/2016 10:15:58 AM
-- Description:	Auto-generated method to insert a zip_codes record.
-- =============================================
CREATE PROCEDURE [dbo].[usp_zip_codes_insert]
	@zip_code CHAR(5),
	@primary_record CHAR(1),
	@population INT,
	@households_per_zip_code INT,
	@white_population INT,
	@black_population INT,
	@hispanic_population INT,
	@asian_population INT,
	@hawaiian_population INT,
	@indian_population INT,
	@other_population INT,
	@male_population INT,
	@female_population INT,
	@persons_per_household DECIMAL(4,2),
	@average_house_value INT,
	@income_per_household INT,
	@median_age DECIMAL(3,1),
	@median_age_male DECIMAL(3,1),
	@median_age_female DECIMAL(3,1),
	@latitude DECIMAL(12,6),
	@longitude DECIMAL(12,6),
	@elevation INT,
	@state CHAR(2),
	@state_full_name VARCHAR(35),
	@city_type CHAR(1),
	@city_alias_abbreviation VARCHAR(13),
	@area_code VARCHAR(55),
	@city VARCHAR(35),
	@city_alias_name VARCHAR(35),
	@county VARCHAR(45),
	@county_fips CHAR(5),
	@state_fips CHAR(2),
	@time_zone CHAR(2),
	@daylight_saving CHAR(1),
	@msa VARCHAR(35),
	@pmsa CHAR(4),
	@csa CHAR(3),
	@cbsa CHAR(5),
	@cbsa_div CHAR(5),
	@cbsa_type CHAR(5),
	@cbsa_name VARCHAR(150),
	@msa_name VARCHAR(150),
	@pmsa_name VARCHAR(150),
	@region VARCHAR(10),
	@division VARCHAR(20),
	@mailing_name CHAR(1),
	@number_of_businesses INT,
	@number_of_employees INT,
	@business_first_quarter_payroll INT,
	@business_annual_payroll INT,
	@business_employment_flag CHAR(1),
	@growth_rank INT,
	@growing_counties_a INT,
	@growing_counties_b INT,
	@growth_increase_number INT,
	@growth_increase_percentage DECIMAL(3,1),
	@cbsa_population INT,
	@cbsa_division_population INT,
	@congressional_district VARCHAR(150),
	@congressional_land_area VARCHAR(150),
	@delivery_residential INT,
	@delivery_business INT,
	@delivery_total INT,
	@preferred_last_line_key VARCHAR(10),
	@classification_code CHAR(1),
	@multi_county CHAR(1),
	@csa_name VARCHAR(150),
	@cbsa_div_name VARCHAR(150),
	@city_state_key CHAR(6),
	@population_estimate INT,
	@land_area DECIMAL(18,6),
	@water_area DECIMAL(18,6),
	@city_alias_code VARCHAR(5),
	@city_mixed_case VARCHAR(35),
	@city_alias_mixed_case VARCHAR(35),
	@box_count INT,
	@sfdu INT,
	@mfdu INT,
	@state_ansi VARCHAR(2),
	@county_ansi VARCHAR(3),
	@zip_intro VARCHAR(15),
	@alias_intro VARCHAR(15),
	@facility_code CHAR(1),
	@city_delivery_indicator CHAR(1),
	@carrier_route_rate_sortation CHAR(1),
	@finance_number VARCHAR(10),
	@unique_zip_name CHAR(1)
AS
BEGIN
	INSERT INTO [zc].[zip_codes]
	(
		[zip_code],
		[primary_record],
		[population],
		[households_per_zip_code],
		[white_population],
		[black_population],
		[hispanic_population],
		[asian_population],
		[hawaiian_population],
		[indian_population],
		[other_population],
		[male_population],
		[female_population],
		[persons_per_household],
		[average_house_value],
		[income_per_household],
		[median_age],
		[median_age_male],
		[median_age_female],
		[latitude],
		[longitude],
		[elevation],
		[state],
		[state_full_name],
		[city_type],
		[city_alias_abbreviation],
		[area_code],
		[city],
		[city_alias_name],
		[county],
		[county_fips],
		[state_fips],
		[time_zone],
		[daylight_saving],
		[msa],
		[pmsa],
		[csa],
		[cbsa],
		[cbsa_div],
		[cbsa_type],
		[cbsa_name],
		[msa_name],
		[pmsa_name],
		[region],
		[division],
		[mailing_name],
		[number_of_businesses],
		[number_of_employees],
		[business_first_quarter_payroll],
		[business_annual_payroll],
		[business_employment_flag],
		[growth_rank],
		[growing_counties_a],
		[growing_counties_b],
		[growth_increase_number],
		[growth_increase_percentage],
		[cbsa_population],
		[cbsa_division_population],
		[congressional_district],
		[congressional_land_area],
		[delivery_residential],
		[delivery_business],
		[delivery_total],
		[preferred_last_line_key],
		[classification_code],
		[multi_county],
		[csa_name],
		[cbsa_div_name],
		[city_state_key],
		[population_estimate],
		[land_area],
		[water_area],
		[city_alias_code],
		[city_mixed_case],
		[city_alias_mixed_case],
		[box_count],
		[sfdu],
		[mfdu],
		[state_ansi],
		[county_ansi],
		[zip_intro],
		[alias_intro],
		[facility_code],
		[city_delivery_indicator],
		[carrier_route_rate_sortation],
		[finance_number],
		[unique_zip_name]
	)
	VALUES
	(
		@zip_code,
		@primary_record,
		@population,
		@households_per_zip_code,
		@white_population,
		@black_population,
		@hispanic_population,
		@asian_population,
		@hawaiian_population,
		@indian_population,
		@other_population,
		@male_population,
		@female_population,
		@persons_per_household,
		@average_house_value,
		@income_per_household,
		@median_age,
		@median_age_male,
		@median_age_female,
		@latitude,
		@longitude,
		@elevation,
		@state,
		@state_full_name,
		@city_type,
		@city_alias_abbreviation,
		@area_code,
		@city,
		@city_alias_name,
		@county,
		@county_fips,
		@state_fips,
		@time_zone,
		@daylight_saving,
		@msa,
		@pmsa,
		@csa,
		@cbsa,
		@cbsa_div,
		@cbsa_type,
		@cbsa_name,
		@msa_name,
		@pmsa_name,
		@region,
		@division,
		@mailing_name,
		@number_of_businesses,
		@number_of_employees,
		@business_first_quarter_payroll,
		@business_annual_payroll,
		@business_employment_flag,
		@growth_rank,
		@growing_counties_a,
		@growing_counties_b,
		@growth_increase_number,
		@growth_increase_percentage,
		@cbsa_population,
		@cbsa_division_population,
		@congressional_district,
		@congressional_land_area,
		@delivery_residential,
		@delivery_business,
		@delivery_total,
		@preferred_last_line_key,
		@classification_code,
		@multi_county,
		@csa_name,
		@cbsa_div_name,
		@city_state_key,
		@population_estimate,
		@land_area,
		@water_area,
		@city_alias_code,
		@city_mixed_case,
		@city_alias_mixed_case,
		@box_count,
		@sfdu,
		@mfdu,
		@state_ansi,
		@county_ansi,
		@zip_intro,
		@alias_intro,
		@facility_code,
		@city_delivery_indicator,
		@carrier_route_rate_sortation,
		@finance_number,
		@unique_zip_name
	)
END