export const REQUEST_ENVIRONMENT = "REQUEST_ENVIRONMENT";
export const RECEIVE_ENVIRONMENT = "RECEIVE_ENVIRONMENT";

export const REQUEST_EMPLOYEE = "REQUEST_EMPLOYEE";
export const RECEIVE_EMPLOYEE = "RECEIVE_EMPLOYEE";

export const TOGGLE_MODAL = "TOGGLE_MODAL";

export const DEPLOY_ERROR = "DEPLOY_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const CREATE_ALERT = "CREATE_ALERT";

export const SET_OVERLAY_LOADING = "SET_OVERLAY_LOADING";
export const SET_OVERLAY_PROCESSING = "SET_OVERLAY_PROCESSING";

export const STORE_FILE = "STORE_FILE";
export const READ_FILE_B64 = "READ_FILE_B64";
export const STORE_FILE_B64 = "STORE_FILE_B64";
export const CLEAR_FILE = "CLEAR_FILE";

export const TOGGLE_DISABLED_DROPZONES = "TOGGLE_DISABLED_DROPZONES";
