CREATE TABLE [dbo].[plan_version_daypart_goals] (
    [id]                      INT        IDENTITY (1, 1) NOT NULL,
    [plan_version_daypart_id] INT        NOT NULL,
    [flight_start_Date]       DATETIME   NOT NULL,
    [flight_end_Date]         DATETIME   NOT NULL,
    [budget]                  MONEY      NOT NULL,
    [target_impression]       FLOAT (53) NOT NULL,
    [target_cpm]              MONEY      NOT NULL,
    [target_rating_points]    FLOAT (53) NOT NULL,
    [target_cpp]              MONEY      NOT NULL,
    [target_universe]         FLOAT (53) NOT NULL,
    [hh_impressions]          FLOAT (53) NOT NULL,
    [hh_cpm]                  MONEY      NOT NULL,
    [hh_rating_points]        FLOAT (53) NOT NULL,
    [hh_cpp]                  MONEY      NOT NULL,
    [hh_universe]             FLOAT (53) NOT NULL,
    [currency]                INT        NOT NULL,
    [coverage_goal_percent]   FLOAT (53) NOT NULL,
    [goal_breakdown_type]     INT        NOT NULL,
    [is_adu_enabled]          BIT        NOT NULL,
    [impressions_per_unit]    FLOAT (53) NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_plan_version_daypart_goals_plan_version_dayparts] FOREIGN KEY ([plan_version_daypart_id]) REFERENCES [dbo].[plan_version_dayparts] ([id]) ON DELETE CASCADE
);

