CREATE TABLE [dbo].[staged_out_of_specs]
(
	[id] [int] IDENTITY(1,1) NOT NULL,
	[unique_id_external] [bigint] NOT NULL,
	[execution_id_external] [varchar](100) NOT NULL,
	[estimate_id] [int] NOT NULL,
	[inventory_source] [varchar](100) NOT NULL,
	[house_isci] [varchar](100) NOT NULL,
	[client_isci] [varchar](100) NOT NULL,
	[client_spot_length] [int] NOT NULL,
	[broadcast_aired_date] [datetime2](7) NOT NULL,
	[aired_time] [int] NOT NULL,
	[station_legacy_call_letters] [varchar](30) NULL,
	[affiliate] [varchar](30) NULL,
	[market_code] [int] NULL,
	[market_rank] [int] NULL,
	[rate] [money] NOT NULL,
	[audience_name] [varchar](127) NOT NULL,
	[impressions] [float] NOT NULL,
	[program_name] [varchar](500) NOT NULL,
	[program_genre] [varchar](127) NOT NULL,
	[reason_code] [int] NOT NULL,
	[reason_code_message] [varchar](500) NULL,
	[lead_in_program_name] [varchar](500) NULL,
	[lead_out_program_name] [varchar](500) NULL,
	[plan_id] [int] NOT NULL,
	[daypart_code] [varchar](10) NULL,
	[start_time] [int] NULL,
	[end_time] [int] NULL,
	[monday] [int] NULL,
	[tuesday] [int] NULL,
	[wednesday] [int] NULL,
	[thursday] [int] NULL,
	[friday] [int] NULL,
	[saturday] [int] NULL,
	[sunday] [int] NULL,
	[ingested_by] [varchar](100) NOT NULL,
	[ingested_at] [datetime] NOT NULL,
	CONSTRAINT [PK_staged_out_of_specs] PRIMARY KEY CLUSTERED ([id] ASC)
);