import { createAction } from '../actionCreator';

export const TRACKER_FILE_UPLOAD = createAction('TRACKER_FILE_UPLOAD');

export const TRACKER_ARCHIVE_UNLIKED_ISCI = createAction('TRACKER_ARCHIVE_UNLIKED_ISCI');
export const TRACKER_UNLINKED_ISCIS_DATA = createAction('TRACKER_UNLINKED_ISCIS_DATA');
export const TRACKER_LOAD_ARCHIVED_ISCI = createAction('TRACKER_LOAD_ARCHIVED_ISCI');
export const TRACKER_LOAD_VALID_ISCI = createAction('TRACKER_LOAD_VALID_ISCI');
export const TRACKER_RESCRUB_UNLIKED_ISCI = createAction('TRACKER_ESCRUB_UNLIKED_ISCI');
export const TRACKER_MAP_UNLINKED_ISCI = createAction('TRACKER_MAP_UNLINKED_ISCI');
export const TRACKER_UNDO_ARCHIVED_ISCI = createAction('TRACKER_UNDO_ARCHIVED_ISCI');
export const TRACKER_CLOSE_UNLINKED_ISCI_MODAL = 'TRACKER_CLOSE_UNLINKED_ISCI_MODAL';

export const TRACKER_REQUEST_UNLINKED_ISCIS_DATA = 'TRACKER_REQUEST_UNLINKED_ISCIS_DATA';
export const TRACKER_RECEIVE_UNLINKED_ISCIS_DATA = 'TRACKER_RECEIVE_UNLINKED_ISCIS_DATA';

export const TRACKER_REQUEST_FILTERED_UNLINKED = 'TRACKER_REQUEST_FILTERED_UNLINKED';
export const TRACKER_RECEIVE_FILTERED_UNLINKED = 'TRACKER_RECEIVE_FILTERED_UNLINKED';

export const TRACKER_REQUEST_FILTERED_ARCHIVED = 'TRACKER_REQUEST_FILTERED_ARCHIVED';
export const TRACKER_RECEIVE_FILTERED_ARCHIVED = 'TRACKER_RECEIVE_FILTERED_ARCHIVED';
