import { createAction } from "../actionCreator";

export const TRACKER_FILE_UPLOAD = createAction("tracker/FILE_UPLOAD");

export const TRACKER_ARCHIVE_UNLIKED_ISCI = createAction(
  "tracker/ARCHIVE_UNLIKED_ISCI"
);
export const TRACKER_UNLINKED_ISCIS_DATA = createAction(
  "tracker/UNLINKED_ISCIS_DATA"
);
export const TRACKER_LOAD_ARCHIVED_ISCI = createAction(
  "tracker/LOAD_ARCHIVED_ISCI"
);
export const TRACKER_LOAD_VALID_ISCI = createAction("tracker/LOAD_VALID_ISCI");
export const TRACKER_RESCRUB_UNLIKED_ISCI = createAction(
  "tracker/RESCRUB_UNLIKED_ISCI"
);
export const TRACKER_MAP_UNLINKED_ISCI = createAction(
  "tracker/MAP_UNLINKED_ISCI"
);
export const TRACKER_UNDO_ARCHIVED_ISCI = createAction(
  "tracker/UNDO_ARCHIVED_ISCI"
);
export const TRACKER_UNDO_SCRUB_STATUS = createAction(
  "tracker/UNDO_SCRUB_STATUS"
);

export const TRACKER_SAVE_NEW_CLIENT_SCRUBS = "tracker/SAVE_NEW_CLIENT_SCRUBS";
export const TRACKER_CLOSE_UNLINKED_ISCI_MODAL =
  "tracker/CLOSE_UNLINKED_ISCI_MODAL";
export const UNDO_SCRUB_STATUS = createAction("tracker/UNDO_SCRUB_STATUS");

export const SAVE_NEW_CLIENT_SCRUBS = "tracker/SAVE_NEW_CLIENT_SCRUBS";
export const CLOSE_UNLINKED_ISCI_MODAL = "tracker/CLOSE_UNLINKED_ISCI_MODAL";

export const REQUEST_TRACKER = "tracker/REQUEST_TRACKER";
export const RECEIVE_TRACKER = "tracker/RECEIVE_TRACKER";

export const REQUEST_ASSIGN_TRACKER_DISPLAY =
  "tracker/REQUEST_ASSIGN_TRACKER_DISPLAY";
export const ASSIGN_TRACKER_DISPLAY = "tracker/ASSIGN_TRACKER_DISPLAY";

export const REQUEST_FILTERED_TRACKER = "tracker/REQUEST_FILTERED_TRACKER";
export const RECEIVE_FILTERED_TRACKER = "tracker/RECEIVE_FILTERED_TRACKER";

export const REQUEST_TRACKER_CLIENT_SCRUBBING =
  "tracker/REQUEST_TRACKER_CLIENT_SCRUBBING";
export const RECEIVE_TRACKER_CLIENT_SCRUBBING =
  "tracker/RECEIVE_TRACKER_CLIENT_SCRUBBING";

export const TRACKER_REQUEST_FILTERED_UNLINKED =
  "tracker/REQUEST_FILTERED_UNLINKED";
export const TRACKER_RECEIVE_FILTERED_UNLINKED =
  "tracker/RECEIVE_FILTERED_UNLINKED";

export const TRACKER_REQUEST_FILTERED_ARCHIVED =
  "tracker/REQUEST_FILTERED_ARCHIVED";
export const TRACKER_RECEIVE_FILTERED_ARCHIVED =
  "tracker/RECEIVE_FILTERED_ARCHIVED";

export const TRACKER_RECEIVE_CLEAR_ISCI_FILTER =
  "tracker/RECEIVE_CLEAR_ISCI_FILTER";
export const RECEIVE_FILTERED_ARCHIVED = "tracker/RECEIVE_FILTERED_ARCHIVED";

export const RECEIVE_CLEAR_ISCI_FILTER = "tracker/RECEIVE_CLEAR_ISCI_FILTER";

export const TRACKER_REQUEST_FILTERED_SCRUBBING_DATA =
  "tracker/REQUEST_FILTERED_SCRUBBING_DATA";
export const TRACKER_RECEIVE_FILTERED_SCRUBBING_DATA =
  "tracker/RECEIVE_FILTERED_SCRUBBING_DATA";
export const TRACKER_REQUEST_CLEAR_SCRUBBING_FILTERS_LIST =
  "tracker/REQUEST_CLEAR_SCRUBBING_FILTERS_LIST";
export const TRACKER_RECEIVE_CLEAR_SCRUBBING_FILTERS_LIST =
  "tracker/RECEIVE_CLEAR_SCRUBBING_FILTERS_LIST";

export const REQUEST_FILTERED_SCRUBBING_DATA =
  "tracker/REQUEST_FILTERED_SCRUBBING_DATA";
export const RECEIVE_FILTERED_SCRUBBING_DATA =
  "tracker/RECEIVE_FILTERED_SCRUBBING_DATA";
export const REQUEST_CLEAR_SCRUBBING_FILTERS_LIST =
  "tracker/REQUEST_CLEAR_SCRUBBING_FILTERS_LIST";
export const RECEIVE_CLEAR_SCRUBBING_FILTERS_LIST =
  "tracker/RECEIVE_CLEAR_SCRUBBING_FILTERS_LIST";

export const TRACKER_REQUEST_UNLINKED_ISCIS_DATA =
  "tracker/REQUEST_UNLINKED_ISCIS_DATA";
export const TRACKER_RECEIVE_UNLINKED_ISCIS_DATA =
  "tracker/RECEIVE_UNLINKED_ISCIS_DATA";
export const RECEIVE_UNLINKED_ISCIS_DATA =
  "tracker/RECEIVE_UNLINKED_ISCIS_DATA";

export const REQUEST_TRACKER_OVERRIDE_STATUS =
  "tracker/REQUEST_TRACKER_OVERRIDE_STATUS";
export const RECEIVE_TRACKER_OVERRIDE_STATUS =
  "tracker/RECEIVE_TRACKER_OVERRIDE_STATUS";

export const TRACKER_REQUEST_SWAP_PROPOSAL_DETAIL =
  "tracker/REQUEST_SWAP_PROPOSAL_DETAIL";
export const TRACKER_RECEIVE_SWAP_PROPOSAL_DETAIL =
  "tracker/RECEIVE_SWAP_PROPOSAL_DETAIL";
export const RECEIVE_SWAP_PROPOSAL_DETAIL =
  "tracker/RECEIVE_SWAP_PROPOSAL_DETAIL";
