import { createAction } from "../actionCreator";

export const TRACKER_FILE_UPLOAD = createAction("TRACKER_FILE_UPLOAD");

export const ARCHIVE_UNLIKED_ISCI = createAction(
  "TRACKER_ARCHIVE_UNLIKED_ISCI"
);
export const UNLINKED_ISCIS_DATA = createAction("TRACKER_UNLINKED_ISCIS_DATA");
export const LOAD_ARCHIVED_ISCI = createAction("TRACKER_LOAD_ARCHIVED_ISCI");
export const LOAD_VALID_ISCI = createAction("TRACKER_LOAD_VALID_ISCI");
export const RESCRUB_UNLIKED_ISCI = createAction(
  "TRACKER_RESCRUB_UNLIKED_ISCI"
);
export const MAP_UNLINKED_ISCI = createAction("TRACKER_MAP_UNLINKED_ISCI");
export const UNDO_ARCHIVED_ISCI = createAction("TRACKER_UNDO_ARCHIVED_ISCI");
export const UNDO_SCRUB_STATUS = createAction("TRACKER_UNDO_SCRUB_STATUS");

export const SAVE_NEW_CLIENT_SCRUBS = "TRACKER_SAVE_NEW_CLIENT_SCRUBS";
export const CLOSE_UNLINKED_ISCI_MODAL = "TRACKER_CLOSE_UNLINKED_ISCI_MODAL";

export const REQUEST_TRACKER = "REQUEST_TRACKER";
export const RECEIVE_TRACKER = "RECEIVE_TRACKER";

export const REQUEST_ASSIGN_TRACKER_DISPLAY = "REQUEST_ASSIGN_TRACKER_DISPLAY";
export const ASSIGN_TRACKER_DISPLAY = "ASSIGN_TRACKER_DISPLAY";

export const REQUEST_FILTERED_TRACKER = "REQUEST_FILTERED_TRACKER";
export const RECEIVE_FILTERED_TRACKER = "RECEIVE_FILTERED_TRACKER";

export const REQUEST_FILTERED_UNLINKED = "TRACKER_REQUEST_FILTERED_UNLINKED";
export const RECEIVE_FILTERED_UNLINKED = "TRACKER_RECEIVE_FILTERED_UNLINKED";

export const REQUEST_FILTERED_ARCHIVED = "TRACKER_REQUEST_FILTERED_ARCHIVED";
export const RECEIVE_FILTERED_ARCHIVED = "TRACKER_RECEIVE_FILTERED_ARCHIVED";

export const RECEIVE_CLEAR_ISCI_FILTER = "TRACKER_RECEIVE_CLEAR_ISCI_FILTER";

export const REQUEST_TRACKER_CLIENT_SCRUBBING =
  "REQUEST_TRACKER_CLIENT_SCRUBBING";
export const RECEIVE_TRACKER_CLIENT_SCRUBBING =
  "RECEIVE_TRACKER_CLIENT_SCRUBBING";

export const REQUEST_FILTERED_SCRUBBING_DATA =
  "TRACKER_REQUEST_FILTERED_SCRUBBING_DATA";
export const RECEIVE_FILTERED_SCRUBBING_DATA =
  "TRACKER_RECEIVE_FILTERED_SCRUBBING_DATA";
export const REQUEST_CLEAR_SCRUBBING_FILTERS_LIST =
  "TRACKER_REQUEST_CLEAR_SCRUBBING_FILTERS_LIST";
export const RECEIVE_CLEAR_SCRUBBING_FILTERS_LIST =
  "TRACKER_RECEIVE_CLEAR_SCRUBBING_FILTERS_LIST";

export const REQUEST_UNLINKED_ISCIS_DATA =
  "TRACKER_REQUEST_UNLINKED_ISCIS_DATA";
export const RECEIVE_UNLINKED_ISCIS_DATA =
  "TRACKER_RECEIVE_UNLINKED_ISCIS_DATA";

export const REQUEST_TRACKER_OVERRIDE_STATUS =
  "REQUEST_TRACKER_OVERRIDE_STATUS";
export const RECEIVE_TRACKER_OVERRIDE_STATUS =
  "RECEIVE_TRACKER_OVERRIDE_STATUS";

export const REQUEST_SWAP_PROPOSAL_DETAIL =
  "TRACKER_REQUEST_SWAP_PROPOSAL_DETAIL";
export const RECEIVE_SWAP_PROPOSAL_DETAIL =
  "TRACKER_RECEIVE_SWAP_PROPOSAL_DETAIL";
