import { createAction } from "Utils/action-creator";

const ROOT = "post-pre-posting";

export const POST_PRE_POSTING_INITIALDATA = createAction(
  `${ROOT}/POST_PRE_POSTING_INITIALDATA`
);
export const POST_PRE_POSTING = createAction(`${ROOT}/POST_PRE_POSTING`);
export const FILTERED_POST_PRE_POSTING = createAction(
  `${ROOT}/FILTERED_POST_PRE_POSTING`
);
export const DELETE_POST_PRE_POSTING = createAction(
  `${ROOT}/DELETE_POST_PRE_POSTING`
);
export const POST_PRE_POSTING_FILE_EDIT = createAction(
  `${ROOT}/POST_PRE_POSTING_FILE_EDIT`
);
export const POST_PRE_POSTING_FILE_SAVE = createAction(
  `${ROOT}/POST_PRE_POSTING_FILE_SAVE`
);
export const POST_PRE_POSTING_FILE_UPLOAD = createAction(
  `${ROOT}/POST_PRE_POSTING_FILE_UPLOAD`
);

export const TOGGLE_MODAL = `${ROOT}/TOGGLE_MODAL`;

export const FILE_EDIT_FORM_UPDATE_EQUIVALIZED = `${ROOT}/FILE_EDIT_FORM_UPDATE_EQUIVALIZED`;
export const FILE_EDIT_FORM_UPDATE_POSTING_BOOK = `${ROOT}/FILE_EDIT_FORM_UPDATE_POSTING_BOOK`;
export const FILE_EDIT_FORM_UPDATE_PLAYBACK_TYPE = `${ROOT}/FILE_EDIT_FORM_UPDATE_PLAYBACK_TYPE`;
export const FILE_EDIT_FORM_UPDATE_DEMOS = `${ROOT}/FILE_EDIT_FORM_UPDATE_DEMOS`;

export const FILE_UPLOAD_FORM_UPDATE_EQUIVALIZED = `${ROOT}/FILE_UPLOAD_FORM_UPDATE_EQUIVALIZED`;
export const FILE_UPLOAD_FORM_UPDATE_POSTING_BOOK = `${ROOT}/FILE_UPLOAD_FORM_UPDATE_POSTING_BOOK`;
export const FILE_UPLOAD_FORM_UPDATE_PLAYBACK_TYPE = `${ROOT}/FILE_UPLOAD_FORM_UPDATE_PLAYBACK_TYPE`;
export const FILE_UPLOAD_FORM_UPDATE_DEMOS = `${ROOT}/FILE_UPLOAD_FORM_UPDATE_DEMOS`;
export const CLEAR_FILE_UPLOAD_FORM = `${ROOT}/CLEAR_FILE_UPLOAD_FORM`;
